import { guide, type ToolGuideCopy } from "@/lib/tools/guides/types"

export const addedGuides: Record<string, ToolGuideCopy> = {
  "crypto-tax-calculator": guide(
    "Buy 0.1 BTC on 15 January 2024 at $60,000, then sell 0.04 BTC on 1 November 2024 at $70,000. FIFO assigns the oldest coins, so the cost of that sale is $2,400 and the proceeds are $2,800. The realised gain is $400.",
    ["Why only FIFO?", "The page always matches a sale to the oldest remaining buy of that coin. It doesn’t offer last-in or a hand-picked parcel."],
    ["What if I sell more than I bought?", "The matched portion is shown, and the row notes that some of the sale had no buy to cover it. That remainder is not given a cost."],
    ["Can I lodge this with the ATO?", "No — this is an estimate from the rows you type. Fees, transfers, and your actual tax rules aren't applied, so don't lodge it as-is."],
  ),
  "crypto-dca-backtest-calculator": guide(
    "$50 of BTC on the first of each month from January 2022 is invested at that day’s close, then valued at the last close in the bundled series. A lump sum puts the whole amount in on the start date instead — same dollars, one buy rather than many.",
    ["Where do the prices come from?", "Daily closes for BTC-USD and ETH-USD from Yahoo Finance, saved with the site. The page names the as-of date of that file. There is no live quote."],
    ["How is this different from the Crypto DCA Calculator?", "That calculator uses an average price and a current price you type. This one walks a historical close series and draws the value over time."],
    ["Are the dollars Australian?", "No. The series is quoted in US dollars, so the amount you enter is treated as USD."],
  ),
  "loot-box-calculator": guide(
    "A $2 pull with an 80% common worth $0.20, an 18% rare worth $2, and a 2% legendary worth $40 has an expected value of $1.32. Against the $2 cost, the pull is worth about −$0.68 on average. The chance of at least one legendary in 10 pulls is about 18%.",
    ["What does expected value mean?", "Each rarity’s chance times its value, added up. It is the average return of one pull if you could repeat the pull many times, not what the next pull will pay."],
    ["How is the chance within N pulls worked out?", "One minus the chance of missing every time: 1 − (1 − rate) to the power of N. Each pull is treated as independent."],
    ["Is this an encouragement to buy?", "No. It is a way to see that a rare prize can still leave the average pull below its price."],
  ),
  "pc-build-cost-estimator": guide(
    "A GPU at $700, a CPU at $400, RAM at $150, storage at $120, a case at $110, a PSU at $130, and a monitor at $280 add up to $1,890. A part you already own stays at $0, so you can leave it off the spend.",
    ["Does this look up current street prices?", "No. Every figure is one you type. Shops, sales, and shipping are outside the total unless you include them in a line."],
    ["Can I add a second monitor or a cooler?", "There is one line per part. Put a combined price in that line, or fold the extra into the closest part."],
    ["Is the total in Australian dollars?", "The labels say AUD. The maths is a plain sum, so the currency is whatever you typed."],
  ),
  "library-value-calculator": guide(
    "Hades at $20 and Stardew Valley at $15 is $35 spent. A free weekend game is $0 if you add it, and a gift is whatever you choose to record.",
    ["Does this connect to Steam?", "No. There is no account and no library import. The names are labels for your own list."],
    ["Should I use the price I paid or today’s price?", "What you paid. The page is a spending total, not a resale valuation."],
    ["What about a bundle?", "Split the bundle across the games, or enter one row for the bundle. The total only adds the numbers you give it."],
  ),
  "bracket-generator": guide(
    "North, South, East, and West make two semis and a final. Click North, then East, then North again in the final, and North is the winner. A list of three names adds a bye so the tree stays even.",
    ["What happens to a bye?", "An empty slot is filled so the bracket is a power of two. The named side moves on without a click."],
    ["Can I save the bracket?", "No. It lives in the page. Refreshing starts again from the names."],
    ["Is it double elimination?", "No. One loss removes a name. There is no losers’ bracket."],
  ),
  "rate-card-calculator": guide(
    "25,000 Instagram followers, a 2.4% engagement rate, and a reel. The page starts from a rough amount per 1,000 followers for that format, nudges it because 2.4% is above a typical Instagram rate, and shows a low and a high.",
    ["Is this what a brand will pay?", "No. It is a starting-point estimate. Usage rights, exclusivity, and how long the piece takes are not in the formula."],
    ["What does the engagement adjustment do?", "It compares your rate with a rough typical rate for that platform, then scales the base up or down inside a limited band."],
    ["Why is the range in US dollars?", "The multipliers are the rough industry-style dollars per 1,000 followers used on this page, quoted in USD. Convert them if you invoice in AUD."],
  ),
  "engagement-rate-calculator": guide(
    "12,000 followers, 240 average likes, and 18 average comments. Interactions are 258, so the rate is 258 ÷ 12,000, which is 2.15%.",
    ["Which interactions count?", "Average likes plus average comments. Saves, shares, and views are not in this version."],
    ["What is a good rate?", "On Instagram, under 1% is quiet for a larger account, 1–3% is a common mid range, and above 3% is strong. Smaller accounts and other platforms often sit elsewhere."],
    ["Should I use one post or an average?", "An average across recent posts. One viral post will overstate the rate you can usually offer."],
  ),
  "best-time-to-post": guide(
    "Instagram, an audience in Australia, clock set to Adelaide: late morning to early afternoon on a weekday, about 10:00–13:00 local time. The same platform with a United States audience uses the same kind of window, on that audience’s clock.",
    ["Are these my best hours?", "No. They are general windows drawn from published industry timing reports. Your own analytics can disagree."],
    ["Does the timezone move the clock?", "The hours are already in the audience’s local time. The timezone tells you which clock to read them on."],
    ["Why do weekdays show up so often?", "Many published benchmarks cluster on weekday mid-morning or early evening. A niche that is online at night will not match that."],
  ),
  "thread-formatter": guide(
    "A note longer than 280 characters, set to X, becomes 1/2, 2/2, and so on. The “1/2 ” prefix is inside the 280, so the words stop earlier than a raw character cut — you won’t blow the limit by accident.",
    ["Why are Threads posts longer?", "The Threads option uses 500 characters. X stays at 280. Neither limit is read from the live platform."],
    ["Does it split mid-word?", "It breaks on spaces. A single word longer than the limit is still placed in its own post."],
    ["Can I post from here?", "No. Each card has a copy button. You paste the text into the platform yourself."],
  ),
  "thumbnail-preview": guide(
    "Upload two stills, set the title to “Saturday build log”, the channel to “Nice Tools”, and the views to “12K”. The two cards show the same caption under different images so you can compare the crop.",
    ["Is this a real feed?", "No. It is a simple side-by-side mock: image, title, channel, and a view count you type."],
    ["Are the images uploaded?", "No. They stay in this browser as local previews."],
    ["Can I judge the safe area for Shorts?", "Only by eye. This page does not overlay a platform’s UI chrome."],
  ),
  "username-checker": guide(
    "Checking “nicebuild” asks Instagram, TikTok, and X from the server. A profile the platform confirms is marked taken. A clear miss is marked looks free. A block, a login wall, or a timeout is “couldn’t check”, not a crash.",
    ["Why not check in the browser?", "Those sites do not allow a page on this domain to ask them directly. The check runs on the server."],
    ["Does “looks free” mean I can register it?", "No. The platform can still reserve the name, or the lookup can be wrong. Confirm on the signup form."],
    ["What if every row says couldn’t check?", "The platforms refused or timed out. Try again later. The page does not guess."],
  ),
  "bio-link-builder": guide(
    "A title of “Nice Tools” plus Site and Newsletter becomes a short preview and a single HTML file. Open the download, or paste the HTML onto a host you already use.",
    ["Is there a public link?", "Not in this version. There is no account and no saved page. The preview and the HTML file are the output."],
    ["Can I style it?", "The download uses a plain layout. Edit the file if you want different colours or fonts."],
    ["Do the links open from the preview?", "Yes, if the address is a full URL. A label without an address still shows in the preview."],
  ),
  "api-cost-calculator": guide(
    "1,000 requests to Claude Sonnet 5, with 800 input tokens and 300 output tokens each. At $2 and $10 per million tokens, the input is $1.60 and the output is $3.00, so the estimate is $4.60.",
    ["How current are the prices?", "They were copied from provider pages on 5 October 2026 and are updated by hand. They can lag. The link under the result is the source of truth."],
    ["Does this include prompt caching?", "No. It uses the standard input and output rates only. Cache hits, batch, and long-context uplifts are extra."],
    ["Why US dollars?", "The providers publish these rates in USD. The figure is not converted to AUD."],
  ),
  "token-counter": guide(
    "The sentence “Count the tokens in this prompt.” is counted with the o200k_base encoding. The number is the token length of that encoding, not a character count.",
    ["Which tokenizer is this?", "gpt-tokenizer, using o200k_base, which recent OpenAI models use. Claude and Gemini will not match it exactly."],
    ["Do spaces and line breaks count?", "Yes, if the encoding gives them tokens. The count is of tokens, not of words."],
    ["Is the number exact for my bill?", "Only if the provider uses this same encoding and you send this exact text. Tool messages, images, and system prompts are not included unless you paste them."],
  ),
  "coding-tool-cost-calculator": guide(
    "Eight hours a week lands in the middle band: Cursor Pro+ at USD 60, Claude Max 5× at USD 100, and Copilot Pro+ at USD 39. Those are published list prices, not a prediction of your invoice.",
    ["How do hours pick a plan?", "Under 5 hours uses the entry paid tier, 5 to 15 the middle tier, and above 15 the top individual tier. That split is a rough comparison, not a vendor rule."],
    ["Can the real bill be higher?", "Yes. Cursor, Copilot, and Claude Code all meter usage beyond the seat. Heavy agent use often costs more than the price on the card."],
    ["When were the prices checked?", "5 October 2026, from Cursor’s pricing page and published Claude and Copilot individual tiers."],
  ),
  "prompt-library": guide(
    "Save a prompt titled “Release notes” with the body you reuse. It appears in the list on this browser. Delete removes it from local storage.",
    ["Will it appear on my phone?", "Only if you saved it in that browser on that phone. Nothing is synced to an account."],
    ["What clears the list?", "Deleting a prompt, or clearing this site’s data in the browser. A private window will not see the saved list."],
    ["Can I export them?", "Copy a prompt from its card. There is no file export in this version."],
  ),
  "subscription-audit-calculator": guide(
    "Streaming at $16 a month and music at $12 a month is $28 a month, which is $336 a year. The year is shown first because that’s the number people under-count.",
    ["Does a yearly plan belong here?", "Turn it into a month first, or type the monthly equivalent. The page multiplies every line by 12."],
    ["What about a free trial?", "Leave it off, or put 0, until it starts billing. A trial is not a monthly cost yet."],
    ["Are price rises included?", "Only if you type the new amount. The page does not know what a service will charge next month."],
  ),
  "expense-splitter": guide(
    "Alex paid $80, Sam paid $20, and Jordan paid $0. The bill is $100, so each share is $33.33. Sam pays Alex $13.33 and Jordan pays Alex $33.33 — Alex is made whole.",
    ["Is the split always equal?", "Yes. Everyone owes the same share of the total, regardless of who ordered what."],
    ["What if someone should pay more?", "This version does not weight shares. Adjust what you type, or settle the difference outside the page."],
    ["Does it remember last week’s dinner?", "No. It settles the people and amounts on the page, then forgets them."],
  ),
  "side-hustle-tracker": guide(
    "A Saturday market takes $180 and the stall fee is $40. Profit is $140. Another expense row reduces that running total.",
    ["Where is the log stored?", "In the page only. Refreshing clears it. It is not a bookkeeping file."],
    ["Does this estimate tax?", "No. It is income minus expenses. Use the gig tax estimator if you want a rough tax figure."],
    ["Can a line be both?", "No. Mark each line income or expense. A refund of an expense is another income line."],
  ),
  "bnpl-cost-calculator": guide(
    "A $240 purchase in 4 instalments with $12 of fees costs $252, so each instalment is $63. The extra $12 is 5% of the price, even when the plan says interest-free.",
    ["Why call out interest-free?", "The advertised rate can be 0% while a fee still increases what you pay. The fee is the cost."],
    ["Is the extra an interest rate?", "It is the fees as a share of the purchase price. It is not a comparison rate and it does not annualise the timing of the instalments."],
    ["What if the fee is zero?", "You pay the purchase price, split by the number of instalments. There is no extra cost on these inputs."],
  ),
  "fire-calculator": guide(
    "$80,000 saved, $50,000 a year of expenses, a 7% return, and a 30% savings rate. The FI number is $1,250,000, which is 25 times expenses. Annual savings are inferred from the rate and the expenses, then the balance is grown year by year.",
    ["What is the 4% rule here?", "The target is annual expenses divided by 0.04. That is the portfolio that would cover spending at a 4% withdrawal."],
    ["How is the savings rate used?", "It is the share of income you keep. Income is expenses divided by one minus that rate, and the difference is what you add each year."],
    ["Is the return guaranteed?", "No. The percent is applied once a year, with no crashes, fees, or tax."],
  ),
  "gig-tax-estimator": guide(
    "A $65,000 wage plus $18,000 of freelance income. Tax is worked on $83,000, then the tax on $65,000 is subtracted, so the difference is the extra tax on the gig. Medicare is a flat 2% in both totals.",
    ["Which year is this?", "2026–27 resident rates published by the ATO: 15% from $18,201 to $45,000, then 30%, 37%, and 45%. The tax-free threshold is still $18,200."],
    ["Does it include deductions?", "No. Enter income after the deductions you already intend to claim, or treat the result as high. The low-income Medicare reduction is not applied."],
    ["Is this a lodgement figure?", "No. It is an estimate, not tax advice. Offsets, HELP, and GST on the freelance work are not in the number."],
  ),
  "round-up-investing-estimator": guide(
    "$280 spent across 14 transactions, with an average round-up of $0.45, sets aside $6.30 a week. That’s about $27 a month and about $328 a year — spare change that adds up if you keep it going.",
    ["What is an average round-up?", "The typical spare change on one transaction, such as $0.40 when a $4.60 coffee rounds to $5. You supply the average."],
    ["Does the weekly spend change the total?", "The dollars set aside come from the transaction count times the average round-up. Spend is only used to show what share of the week that is."],
    ["Is the money invested?", "No. The page estimates the micro-investment total. It does not buy anything."],
  ),
  "resale-profit-calculator": guide(
    "Sell an item for $45 that cost $12, pay $8 shipping, and use the eBay preset of 13.6%. The fee is $6.12, so the profit is $18.88, a margin of about 42% of the sale price.",
    ["What do the presets assume?", "eBay starts at 13.6%, Depop at 10%, and Vinted at 0% because the buyer often pays the protection fee. Change the percent if your account differs."],
    ["Is margin the same as markup?", "The margin here is profit divided by the sale price, the same idea as the margin calculator. It is not profit divided by cost."],
    ["Does shipping the buyer paid belong here?", "Only the shipping you pay is a cost. If the buyer covers postage, leave that line at 0 or reduce it."],
  ),
  "social-battery-checkin": guide(
    "Answer that you want an early night, that tonight feels like too much, and that the week has been stacked. The page says you are probably due for some downtime.",
    ["Is there a score?", "No. Two or three rest-leaning answers point to downtime, one is a quieter evening, and none is a read that you still have some charge."],
    ["Is this the work style quiz?", "No. That quiz is about how you work with other people. This one is three questions about social energy."],
    ["Should I cancel plans because of it?", "Not on this alone. It is a light prompt, not advice."],
  ),
  "screen-time-audit": guide(
    "1.5 hours of social, 1 hour of video, 0.5 of games, 6 of work, and 0.5 of other is 9.5 hours a day. That’s 66.5 hours a week and 3,468 hours a year — about 144 twenty-four-hour days.",
    ["Where does the year come from?", "The daily total times 365. The week is the day times 7. There is no screen-time permission and no device reading."],
    ["Should work hours be included?", "Only if you want them in the total. Set work to 0 if you are auditing leisure screens."],
    ["What if the day is not typical?", "The page treats the hours as every day. Use a typical day, or average a heavy day and a light one before you type."],
  ),
  "carbon-footprint-estimator": guide(
    "7 hours of streaming a week is 364 hours a year. At 36 grams of CO2 per hour, that is about 13.1 kg. Twenty AI prompts a day at 0.03 grams each is about 0.22 kg a year.",
    ["Where does 36 grams come from?", "The IEA’s updated estimate for one hour of streaming video in 2019, on a global average grid, from its December 2020 commentary. Later grids and resolutions differ."],
    ["Where does the AI figure come from?", "0.03 grams of CO2e per median Gemini Apps text prompt, from Google’s May 2025 measurement. It is not your model and not your electricity grid."],
    ["Why so round?", "These are illustrative factors, not a meter reading. Do not treat the kilograms as a precise footprint."],
  ),
  "commit-message-generator": guide(
    "Type feat, scope tools, subject “add a FIFO crypto tax calculator”. The message is `feat(tools): add a FIFO crypto tax calculator`. A body, if you add one, sits under a blank line.",
    ["Does it look at the diff?", "No. It only formats the type, scope, subject, and body you type."],
    ["What if I leave the scope empty?", "The parentheses are omitted: `fix: correct the total`."],
    ["Which types are available?", "feat, fix, chore, docs, refactor, test, and style. That is the conventional set this page offers."],
  ),
  "rate-limit-calculator": guide(
    "1,000 requests each 60 seconds, 40 users, 20 requests each. Demand is 800, so the cap holds, with 200 requests of room, and the count resets after 60 seconds. At 20 requests each, the cap covers 50 users.",
    ["What does “until reset” mean?", "The length of the window. The page does not know when the current window started, so it reports how long a full window is."],
    ["What if users do not all call at once?", "The calculator assumes every concurrent user spends their full request count inside the same window. Spread-out traffic uses less of the cap."],
    ["Is a short result a failure?", "It means demand is above the cap. Fewer requests per user, or a higher cap, is what changes the verdict."],
  ),
  "ai-tool-fit-quiz": guide(
    "Answers that stay in the editor, want a choice of models, and switch models locally lean to Cursor. Answers that want a terminal agent and command running lean to Claude Code. Answers that stay on the line and in GitHub lean to Copilot.",
    ["Does this change the work style quiz?", "No. That quiz and its questions are untouched. This is a separate four-question read."],
    ["What breaks a tie?", "The tool with the most answers wins. If two tie, the order Cursor, then Claude Code, then Copilot decides."],
    ["Is the result a recommendation to buy?", "It is a preference read from the answers. Pricing and limits change, and the coding-tool cost calculator is the rough price comparison."],
  ),
}
