import { guide, type ToolGuideCopy } from "@/lib/tools/guides/types"

export const businessGuides: Record<string, ToolGuideCopy> = {
  "invoice-generator": guide(
    "One line, “Design and documentation”, quantity 1 at $1,200, plus 10% tax, gives you a $1,200 subtotal, $120 tax, and a $1,320 total. Print opens the browser’s print dialog so you can send it from there.",
    ["Does print make a PDF?", "Choose “Save as PDF” in the print dialog and you’ll have a file. The page doesn’t upload the invoice anywhere."],
    ["Is the tax GST?", "It’s whatever percent you type. For Australian GST, use 10 and put GST in the description if you need the word on the page."],
    ["Can I add more than one line?", "Yes. Each line has a description, a quantity, and a rate. The amount is quantity times rate, so you can stack as many as you need."],
  ),
  "quote-builder": guide(
    "A quote numbered Q-001 with one line at $1,200 and 10% tax totals $1,320 — the same arithmetic as an invoice. The printed page is labelled Quote rather than Invoice, so the two don’t get mixed up.",
    ["What is the difference between a quote and an invoice?", "On this site, the layout is the same and the heading changes. A quote is an offer. An invoice asks to be paid."],
    ["Are the numbers stored?", "No. They live in the page until you refresh. Print or save a PDF if you need a copy to keep."],
    ["Can the tax be zero?", "Yes. Set tax to 0 and the total equals the subtotal."],
  ),
  "margin-calculator": guide(
    "A cost of $40 and a sell price of $65 is $25 profit. Margin is 25 ÷ 65, about 38.5%. Markup is 25 ÷ 40, which is 62.5% — same dollars, two different stories.",
    ["What is the difference between margin and markup?", "Margin divides profit by the sell price. Markup divides profit by the cost. The same dollars produce a higher markup percent than margin percent."],
    ["What if the sell price is below cost?", "Profit is negative, and so are margin and markup. That’s a loss, and you’ll see it shown that way."],
    ["Does this include GST?", "No. Use prices that are both inclusive or both exclusive, so the margin isn’t mixed."],
  ),
  "resume-builder": guide(
    "A name, a role, a contact line, a two-sentence summary, and a short experience block print as a one-page resume — enough to get you out the door. The print dialog can save it as a PDF.",
    ["Will this design the resume for me?", "It sets a simple serif page. It doesn’t rewrite your experience or pick a template library."],
    ["How long should the summary be?", "Two or three lines is plenty. The page will print whatever you type, so a long block becomes a long page."],
    ["Is the resume stored?", "No. Copy the text somewhere else, or save the PDF, before you close the tab."],
  ),
  "cover-letter-generator": guide(
    "Name Ada North, role Product designer, company Northwind, plus a reason and a proof point, and you’ll get a short letter that opens with the application and closes with an invitation to talk.",
    ["Does this write the letter with AI?", "No. It assembles the sentences from the fields you fill in. The wording is yours."],
    ["Can I edit the result?", "Change the fields and the letter updates as you go. Print when it reads the way you want."],
    ["Where does the letter go?", "Only to the print dialog. Nothing is emailed or stored."],
  ),
  "receipt-generator": guide(
    "Workshop $80 and Materials $24 give you a $104 subtotal. At 10% tax the tax is $10.40 and the total is $114.40. Print hands you a receipt with those lines.",
    ["How do I enter a line?", "A name, then the amount, such as Workshop, 80. One line each."],
    ["Can a line be a refund?", "Yes. A negative amount reduces the subtotal, so you can show a refund on the same receipt."],
    ["Does this send the receipt to a customer?", "No. Print it, or save a PDF, and send that yourself."],
  ),
  "qr-code-generator": guide(
    "The URL https://nice-build-ten.vercel.app becomes a square code. Point a phone camera at it and it should open that address. Download saves a PNG of the same code.",
    ["What can I encode?", "Any text or URL that fits in a QR code. A very long string is rejected, so keep it reasonably short."],
    ["Does the code expire?", "No. It only contains the text you typed. If the page at that URL moves, the code still points at the old address."],
    ["Is the image tracked?", "No. The code is drawn in your browser. Scanning it later is just a camera reading the text."],
  ),
  "break-even-calculator": guide(
    "Fixed costs of $8,000, a price of $120, and a variable cost of $45 leave $75 per sale. You cover the fixed costs at 107 sales, because 8,000 ÷ 75 rounds up to 107 — that last fraction of a sale still counts as a whole one.",
    ["What is the contribution?", "Price minus variable cost. That’s what each sale contributes toward the fixed costs."],
    ["Why does it round up?", "You can’t make a fraction of a sale to cover the last dollars, so the unit count is rounded up."],
    ["What if the price is below the variable cost?", "There is no break-even. Every sale increases the loss, and the page says so."],
  ),
  "commission-calculator": guide(
    "$4,800 of sales at 8% commission is $384. The commission is the sales amount times the rate — nothing else is mixed in.",
    ["Is the rate on revenue or on profit?", "On the sales amount you enter. Subtract costs yourself if the agreement pays commission on margin."],
    ["Can I split commission across people?", "Run it once, then divide the result. The page applies one rate to one amount."],
    ["Does this include tax on the commission?", "No. It’s the commission itself, before any tax you owe on it."],
  ),
  "youtube-rpm-calculator": guide(
    "100,000 views at an RPM of $3.50 is $350. RPM is revenue per thousand views, so your earnings are views ÷ 1,000 × RPM.",
    ["What is RPM?", "Revenue per mille: how much you earn for every 1,000 views, after the platform’s cut if that’s how your dashboard defines it."],
    ["Why is the default $3.50?", "It’s a placeholder so the page isn’t empty. Replace it with the RPM from your own analytics."],
    ["Does this predict next month?", "No. It multiplies the views and RPM you type. It doesn’t look at a channel."],
  ),
  "tiktok-earnings-calculator": guide(
    "100,000 views at an RPM of $0.40 is $40. Short-form RPMs are often lower than long-form, so the default here is lower than the YouTube page. Use your own number — that’s the one that matters.",
    ["Is TikTok RPM the same as YouTube RPM?", "The formula is the same: views ÷ 1,000 × RPM. The RPM itself usually isn’t."],
    ["Where do I find my RPM?", "In the platform’s earnings or analytics report. This page doesn’t connect to an account."],
    ["Do views include replays?", "Only if they’re included in the view count you type. The calculator doesn’t adjust for that."],
  ),
  "creator-rate-calculator": guide(
    "20,000 followers, 3% engagement, and a base of $10 per thousand followers is 20 × 3 × 10, which is $600. Change the base to match what you actually charge.",
    ["What is the formula?", "Followers ÷ 1,000, times the engagement percent, times the base dollar amount."],
    ["Is this what I should invoice?", "It’s a starting point for a conversation. Niche, usage rights, and production time move the real rate."],
    ["What does engagement mean here?", "The percent you type, such as likes and comments divided by followers. The page doesn’t fetch it for you."],
  ),
  "paypal-fee-calculator": guide(
    "On $100, a 2.6% fee plus $0.30 is $2.90, so you keep $97.10. Replace the percent and the fixed fee with the rate on your own account.",
    ["Are these PayPal’s current fees?", "The defaults are a common domestic starting point. PayPal’s rate depends on country, currency, and account type, so edit them to match yours."],
    ["Does this include currency conversion?", "No. Conversion is often a separate percent. Add it into the percent field if you want it in the total."],
    ["Is the fee taken from the buyer or the seller?", "This page subtracts the fee from the amount, which matches a seller receiving a payment."],
  ),
  "stripe-fee-calculator": guide(
    "On $100, 1.7% plus $0.30 is $2.00, so you keep $98.00. Australian domestic cards are often near that default. International cards are usually higher, so check yours.",
    ["Why 1.7%?", "It matches a common Australian domestic card rate. Your Stripe pricing page is the source of truth, and both fields are editable."],
    ["Does this include GST on the fee?", "No. If Stripe adds GST on top of the processing fee, increase the percent or the fixed amount to suit."],
    ["What about refunds?", "A refund often returns the amount but not the fee. This page only prices a single successful charge."],
  ),
  "etsy-fee-calculator": guide(
    "A $48 sale with a $16 cost, a $0.20 listing fee, 6.5% transaction, and 3% plus $0.25 payment, comes to about $5.01 in fees and about $26.99 profit. Tick offsite ads if you want to add 12%.",
    ["Are Etsy fees fixed?", "No. Listing, transaction, payment, and offsite ads all change. The defaults are a starting point you should edit."],
    ["What does offsite ads add?", "12% of the sale price, on top of the other fees, when that box is ticked."],
    ["Is profit after my costs?", "Yes. Profit is sale price, minus your cost, minus the fees."],
  ),
  "ebay-fee-calculator": guide(
    "An $80 sale with a $30 cost, a 13.6% final value fee, and 2.6% plus $0.30 payment, is about $13.26 in fees. Profit is about $36.74, which is roughly 46% of the sale price — the bit you actually keep.",
    ["What is a final value fee?", "eBay’s percent of the sale. Categories differ, so replace 13.6% with the rate for your category."],
    ["Does this include postage?", "Only if postage is inside the sale price you type. A separate postage charge isn’t added."],
    ["Is the insertion fee included?", "No. Add a listing or insertion fee into your cost if you want it in the profit."],
  ),
  "amazon-fba-calculator": guide(
    "A $39 sale, $12 product cost, 15% referral, and a $6.50 fulfilment fee leaves $14.65 profit. Referral is a percent of the sale. Fulfilment is a flat amount you type in.",
    ["What is the referral fee?", "Amazon’s percent of the sale price, which depends on the category. 15% is a common default, not a promise."],
    ["What should I put in the fulfilment fee?", "The FBA pick-and-pack fee for that size and weight, from Amazon’s current rate card."],
    ["Does this include storage or returns?", "No. Add those into the product cost, or subtract them from profit afterwards."],
  ),
  "shopify-margin-calculator": guide(
    "A $64 sale with a $22 product cost, 1.6% payment, and a $0.30 fixed fee has about $1.32 in payment fees. Profit is about $40.68, near 64% of the sale — a useful sense-check before you list it.",
    ["Does this include the Shopify subscription?", "No. It prices one order. Spread the monthly plan across your orders separately if you want it in the margin."],
    ["Why is the payment default 1.6%?", "It’s close to a common Shopify Payments domestic rate in Australia. Your plan’s rate may differ."],
    ["Should the price include GST?", "Use the same basis for price and cost. Mixing a tax-inclusive price with a tax-exclusive cost overstates profit."],
  ),
  "upwork-fee-calculator": guide(
    "On a $100 payment with a 10% service fee and no fixed fee, the fee is $10 and you keep $90 — that’s the bit that lands after the platform cut.",
    ["Is Upwork’s fee still 10%?", "Treat 10% as a default you can edit. Upwork has changed its fee structure before, and contracts can differ."],
    ["Does this include the withdrawal fee?", "No. A bank or payment withdrawal can be a separate charge. Add it as the fixed fee if you want it included."],
    ["Is the percent on the client’s total or my rate?", "On the amount you type. If the client also pays a marketplace fee, that isn’t deducted here unless you include it."],
  ),
  "fiverr-fee-calculator": guide(
    "On a $100 order with a 20% fee, Fiverr-style, the fee is $20 and you keep $80. Edit the percent if your account is different.",
    ["Is 20% the current Fiverr fee?", "It’s the usual seller fee people plan with. Confirm it on your account, and edit the field if it has changed."],
    ["Does this include buyer service fees?", "No. This subtracts the seller’s fee from the order amount."],
    ["What about tips or extras?", "Add them into the amount first. The percent applies to the whole amount you enter."],
  ),
  "gumroad-fee-calculator": guide(
    "On a $20 product, 10% plus $0.50 is $2.50, so you keep $17.50. Check your dashboard if those defaults don’t match.",
    ["Is Gumroad’s fee 10% plus 50 cents?", "That’s the default here. Gumroad has offered different rates, so check your dashboard and edit the fields."],
    ["Does the fixed fee apply once per sale?", "Yes. It’s added once to the percent of the amount."],
    ["Are payment processing fees extra?", "If your account charges them separately, add them to the percent or the fixed fee."],
  ),
  "kickstarter-fee-calculator": guide(
    "A $40 pledge with a 5% platform fee, a 3% payment fee, and $0.30 fixed is $3.50 in fees, so $36.50 remains — before you’ve made the reward.",
    ["When does Kickstarter take its fee?", "On collected pledges if the project funds. This page prices a single pledge. It doesn’t model a failed campaign."],
    ["Are payment fees included in the 5%?", "Not here. Platform and payment are separate percents, plus a fixed amount, because that’s how the charges are usually described."],
    ["Does this include reward costs?", "No. Subtract manufacturing and shipping from what you keep if you want profit rather than funds received."],
  ),
}
