import { guide, type ToolGuideCopy } from "@/lib/tools/guides/types"

export const developerGuides: Record<string, ToolGuideCopy> = {
  "json-formatter": guide(
    "Paste {\"name\":\"Ada\",\"ok\":true}. Pretty-print turns it into an indented document. Minify puts it back on one line. An extra comma is reported as invalid JSON.",
    ["Does formatting change the data?", "Nope — it only changes whitespace. Keys, strings, and numbers stay the same."],
    ["Is my JSON uploaded?", "Nope — parsing and formatting happen in your browser."],
    ["Why was valid-looking JSON rejected?", "JSON needs double quotes around keys and strings, and it doesn't allow trailing commas or comments."],
  ),
  "uuid-generator": guide(
    "Ask for 3 identifiers and you'll get three UUID version 4 strings, each with the version nibble set to 4. Copy one, or copy the whole list.",
    ["What version of UUID is this?", "Version 4, from the browser’s crypto.randomUUID. The values are random, not time-based."],
    ["Are these safe to use as database keys?", "Yes for the usual unique-id job. They’re not a secret, and they’re not sortable by time."],
    ["Can I generate more than one?", "Yes. Set a count from 1 to 20 and copy the list."],
  ),
  "regex-tester": guide(
    "The pattern \\d+ against “Order 14 and 2” with the g flag finds 14 and 2. Without g, you'll only see the first match. An unclosed bracket shows the browser’s syntax error.",
    ["Which regex flavour is this?", "JavaScript. Lookbehind and named groups work when your browser supports them. Some other languages differ."],
    ["What do the flags do?", "g finds every match, i ignores case, m changes how ^ and $ treat lines, s lets a dot match a newline, u turns on Unicode mode."],
    ["Does a match include the groups?", "Yes. Each match lists the full text and any capturing groups."],
  ),
  "password-generator": guide(
    "A length of 16 with numbers and symbols might produce something like kP7n-wQ2mX!a4Rde. Each click of Generate draws a new password. Nothing is stored.",
    ["How random is the password?", "Characters are chosen with crypto.getRandomValues in your browser, not a guessable seed."],
    ["Why are some letters missing?", "O, 0, I, l, and 1 are left out so a password is easier to read if you have to type it."],
    ["Is the password sent anywhere?", "Nope — it's created locally. Copy it into your password manager yourself."],
  ),
  "base64-encoder": guide(
    "The text “Nice Build” encodes to TmljZSBCdWlsZA==. Decoding that string returns “Nice Build”. Unicode characters are encoded as UTF-8 bytes first.",
    ["Is Base64 encryption?", "Nope — anyone can decode it. Use it to carry bytes through a text channel, not to hide a secret."],
    ["Why do I see padding equals signs?", "Base64 length is a multiple of 4. The = characters fill the last block. They’re part of a normal encoding."],
    ["Can I decode a data URL?", "Paste only the Base64 portion, after the comma. The data:image/png;base64, prefix isn’t part of the payload."],
  ),
  "url-encoder": guide(
    "The text a b&c=d encodes to a%20b%26c%3Dd. Decoding that string returns a b&c=d. Spaces, ampersands, and equals signs are escaped so they don’t break a query string.",
    ["Encode or encodeURI?", "This uses encodeURIComponent, which also escapes characters such as &, =, and ?. That’s what you want for a single query value."],
    ["What happens to Unicode?", "Characters such as é become UTF-8 percent sequences, for example %C3%A9."],
    ["Why did decoding fail?", "A % must be followed by two hex digits. A stray % or a truncated sequence is invalid."],
  ),
  "timestamp-converter": guide(
    "The Unix time 1760000000 is 9 October 2025, 10:26 UTC. Paste 2026-10-03T09:00 instead and you’ll get the same moment as seconds and as milliseconds.",
    ["Seconds or milliseconds?", "A value with more than 10 digits is treated as milliseconds. Shorter values are treated as seconds."],
    ["Which timezone is “local”?", "The timezone of the browser. UTC is shown separately as an ISO string."],
    ["What date format can I type?", "Something the browser can parse, such as 2026-10-03T09:00. A bare date is interpreted in local time."],
  ),
  "hash-generator": guide(
    "SHA-256 of the text “Nice Build” is a 64-character hex string. The same text always produces the same hash. Change one character and the hash changes completely.",
    ["Which algorithms are available?", "SHA-1, SHA-256, SHA-384, and SHA-512, through the browser’s Web Crypto API. MD5 is not included."],
    ["Can I use this to store passwords?", "Nope — these are fast hashes. Password storage needs a slow hash such as Argon2 or bcrypt, plus a salt."],
    ["Does the hash leave the browser?", "Nope — the digest is computed locally from the text in the box."],
  ),
  "jwt-decoder": guide(
    "The sample token decodes to a header of {\"alg\":\"none\"} and a payload of {\"sub\":\"demo\"}. The third part, the signature, is shown only as text. It isn’t checked.",
    ["Does this verify the token?", "Nope — it only Base64-decodes the header and payload. A valid-looking payload can still be forged."],
    ["What are the three parts?", "Header, payload, and signature, separated by dots. The first two are JSON. The signature is binary and isn’t decoded as JSON."],
    ["Why did decoding fail?", "The header and payload must be Base64url JSON. A token with fewer than two segments, or with damaged padding, will not parse."],
  ),
  "json-validator": guide(
    "{\"ok\": true} is valid JSON. {ok: true} is not, because the key is unquoted. A trailing comma after the last property is also invalid.",
    ["What counts as valid JSON?", "The JSON grammar: objects, arrays, strings in double quotes, numbers, true, false, and null. No comments and no trailing commas."],
    ["Does a successful check format the document?", "Nope — this page only reports whether it parses. Use the JSON Formatter to pretty-print it."],
    ["Will it tell me the line of the error?", "It shows the parser message from the browser, which often includes a position."],
  ),
  "sql-formatter": guide(
    "select id, name from tools where status = 'live' order by name becomes a statement with SELECT, FROM, WHERE, and ORDER BY each starting a line.",
    ["Does this understand every SQL dialect?", "Nope — it breaks major clauses onto their own lines and uppercases those keywords. It’s a readability pass, not a full parser."],
    ["Will it change string contents?", "It rewrites whitespace and the clause keywords it recognises. Check quoted text if a keyword appears inside a string."],
    ["Can I format a stored procedure?", "Short statements format cleanly. Large scripts with several statements may only pick up the clauses it knows."],
  ),
  "xml-formatter": guide(
    "<tools><tool id=\"1\">Nice</tool></tools> indents to a tools element with one tool child. A missing closing tag is reported instead of a formatted document.",
    ["Is the XML uploaded?", "Nope — the browser’s XML parser reads it locally."],
    ["Are attributes preserved?", "Yes. Attributes stay on the opening tag. Child elements are indented underneath."],
    ["Why was my XML rejected?", "It has to be well-formed: matching tags, quoted attributes, and a single root element."],
  ),
  "cron-expression-generator": guide(
    "Minute 0, hour 9, weekdays produces 0 9 * * 1-5, which runs at 09:00 Monday to Friday. Every 15 minutes, every hour, every day produces */15 * * * *.",
    ["What cron format is this?", "The five-field form: minute, hour, day of month, month, day of week. Day of month and month stay as *."],
    ["Does “weekdays” include Saturday?", "Nope — 1-5 is Monday through Friday. Sunday is 0."],
    ["Will this match my scheduler?", "Most Unix crons use these five fields. Some hosted schedulers add a seconds field at the front. Check before you paste it in."],
  ),
  "html-encoder": guide(
    "<p class=\"hi\">Hello</p> encodes to &lt;p class=&quot;hi&quot;&gt;Hello&lt;/p&gt;. Decoding that string returns the original tags.",
    ["When should I encode HTML?", "When you need to show markup as text, or place untrusted text inside HTML, so tags aren’t treated as elements."],
    ["Which characters are escaped?", "Ampersand, less-than, greater-than, and double quote. Apostrophes are left as-is."],
    ["Is this a sanitiser for innerHTML?", "Encoding is the right step before inserting text. Don’t decode and then inject the result as HTML."],
  ),
  "code-beautifier": guide(
    "{\"name\":\"Nice\",\"tools\":[1,2]} pretty-prints as indented JSON. A brace snippet that isn’t JSON is indented by braces instead, with each { and } on its own line.",
    ["Does it format every language?", "JSON is formatted properly when it parses. Anything else gets a simple brace indent, which suits JavaScript-like code and not Python."],
    ["Will it fix syntax errors?", "Nope — invalid JSON falls through to the brace indenter. It doesn’t repair missing commas or quotes."],
    ["Is the code uploaded?", "Nope — formatting runs in the browser."],
  ),
  "json-to-csv": guide(
    "An array of {\"name\":\"Ada\",\"role\":\"Design\"} and {\"name\":\"Lin\",\"role\":\"Build\"} becomes a header row name,role and one row per object.",
    ["What JSON shape is required?", "An array of objects. A single object, or an array of strings, is rejected."],
    ["How are missing keys handled?", "The header is the union of every key. A missing value becomes an empty cell."],
    ["Are commas inside values escaped?", "Yes. A value that contains a comma, quote, or newline is wrapped in quotes, and quotes inside it are doubled."],
  ),
  "csv-to-json": guide(
    "A header name,role followed by Ada,Design and Lin,Build becomes an array of two objects, each with name and role.",
    ["Does the first row have to be a header?", "Yes. Those cells become the object keys. Later rows become the values."],
    ["How are quoted commas handled?", "A quoted cell can contain commas. A doubled quote inside a quoted cell is one quote character."],
    ["What if a row is shorter than the header?", "Missing cells become empty strings. Extra cells beyond the header are dropped."],
  ),
  "yaml-validator": guide(
    "name: Ada, then a list under tags, is valid. A tab indent is rejected. A | block scalar is rejected, because multi-line text isn’t supported on this page.",
    ["What YAML is accepted?", "Maps, lists, quoted strings, numbers, true, false, and null, indented with spaces."],
    ["Why are tabs rejected?", "YAML indent is defined in spaces. A tab is reported with a line number so you can replace it."],
    ["Does valid YAML here match every parser?", "Not always. Anchors, tags, and multi-line blocks are intentionally unsupported, so a file can pass another parser and fail here."],
  ),
  "yaml-to-json": guide(
    "name: Ada and a list of two tags becomes {\"name\":\"Ada\",\"tags\":[\"a\",\"b\"]}. Nested keys keep their structure.",
    ["Are numbers kept as numbers?", "Yes. Unquoted integers and decimals become JSON numbers. Quoted values stay strings."],
    ["What happens to yes and no?", "They stay strings. Only the words true, false, null, and ~ have special meaning here."],
    ["Can I convert a Kubernetes manifest?", "Simple manifests often work. Files that use anchors or multi-line | blocks will stop at the first unsupported line."],
  ),
  "robots-txt-generator": guide(
    "User agent *, allow /, disallow /private, and a sitemap URL produces a robots.txt with those four lines. Blank lines in the path boxes are skipped.",
    ["Does this publish the file?", "Nope — it only writes the text. Save it as robots.txt at the root of your site."],
    ["What does Disallow: /private mean?", "Paths that start with /private are asked to stay out. Crawlers may still ignore the file. It isn’t access control."],
    ["Can I target one bot?", "Change the user agent from * to the bot’s token, such as Googlebot. This form writes a single group."],
  ),
  "chmod-calculator": guide(
    "Owner read, write, and execute, plus group and public read and execute, is 755 and rwxr-xr-x. Clearing public execute changes it to 754 and rwxr-xr--.",
    ["How is the octal number built?", "Each of owner, group, and public is read 4, write 2, and execute 1. Add the bits you tick. 7 is read+write+execute."],
    ["What does the symbol form mean?", "Nine characters in order: owner, group, then everyone else. A letter means that permission is on. A dash means it is off."],
    ["Does this change files on my computer?", "Nope — it only shows the mode. Apply it yourself with chmod if you need to."],
  ),
  "subnet-calculator": guide(
    "192.168.1.40/24 sits in 192.168.1.0 to 192.168.1.255. The usable hosts run from .1 to .254, which is 254 addresses. The mask is 255.255.255.0.",
    ["What is a prefix?", "The number of leading 1-bits in the mask. /24 means the first 24 bits are the network."],
    ["Why are there two fewer usable hosts than addresses?", "For prefixes of /30 and wider, the network address and the broadcast address are reserved. /31 and /32 are treated as special cases."],
    ["Does this support IPv6?", "Nope — enter an IPv4 address and a prefix from 0 to 32."],
  ),
  "cidr-calculator": guide(
    "10.0.0.8/22 belongs to the network 10.0.0.0. The broadcast is 10.0.3.255, the mask is 255.255.252.0, and there are 1,022 usable hosts.",
    ["How do I type a CIDR?", "Address, a slash, then the prefix, such as 10.0.0.8/22."],
    ["What is the difference between this and the subnet calculator?", "This page takes the address and prefix in one field. The subnet calculator takes them separately. The arithmetic is the same."],
    ["Can the address be any host in the block?", "Yes. The network address is calculated from the prefix, so the host bits you type don’t change the network."],
  ),
  "jsonpath-tester": guide(
    "Against {\"tools\":[{\"name\":\"Tip\"},{\"name\":\"Dice\"}]}, the path $.tools[*].name returns [\"Tip\",\"Dice\"]. $.tools[0].name returns [\"Tip\"].",
    ["Which JSONPath features work?", "$.key, bracket indexes, [*], quoted keys, and ..key for a deep search. Filters and script expressions are not supported."],
    ["Why is the result always an array?", "The path can match more than one node, so every match is returned in a list, even when there is only one."],
    ["What does $ mean?", "The root of the document. A path has to start with it."],
  ),
  "csp-header-generator": guide(
    "default-src 'self', script-src 'self', style-src 'self', img-src 'self' data:, and connect-src 'self' join into one Content-Security-Policy value separated by semicolons.",
    ["Where do I put the result?", "In a Content-Security-Policy HTTP header, or in a meta tag. The page gives you the header value."],
    ["What does 'self' allow?", "Resources loaded from the same origin as the page. It doesn’t allow inline scripts unless you add that source yourself."],
    ["Will this header break my site?", "A strict policy can block inline scripts, analytics, and font hosts. Try it in report-only mode before you enforce it."],
  ),
  "utm-link-builder": guide(
    "https://example.com/tools with source newsletter, medium email, and campaign spring becomes a URL whose query includes utm_source, utm_medium, and utm_campaign. Empty fields are left off.",
    ["What are UTM parameters for?", "They label a link so analytics can tell which campaign, medium, and source sent the visit."],
    ["Do I have to fill every field?", "Nope — source, medium, and campaign are the usual set. Term and content are optional and omitted when blank."],
    ["Will this replace parameters already on the URL?", "It sets the UTM keys you fill in. Other query parameters on the URL are kept."],
  ),
}
