import { guide, type ToolGuideCopy } from "@/lib/tools/guides/types"

export const filesDesignVizGuides: Record<string, ToolGuideCopy> = {
  "image-compressor": guide(
    "Take a 4 MB photo, save it again as a JPEG at about 70% quality with no edge longer than 2,400 pixels, and you'll often land well under 1 MB. Your original file stays put.",
    ["Is the image uploaded?", "No — it's redrawn on a canvas in your browser, then offered as a download."],
    ["Why is the result a JPEG?", "The compressor saves JPEG so the quality slider can shrink the file. If your image has transparency, that's flattened onto white."],
    ["Will this hurt print quality?", "For large prints, you'll want the original. The size cap and the quality slider are meant for screens and the web."],
  ),
  "exif-stripper": guide(
    "A phone photo can carry GPS coordinates in its EXIF. Redraw it as a new JPEG and that metadata is dropped. You download a new file, and the original stays where it was.",
    ["What is removed?", "Anything that lived in the file metadata, including camera model and location, because the pixels are copied onto a fresh canvas and saved again."],
    ["Does the picture look the same?", "It's saved as a high-quality JPEG, so you may see a small compression change. The framing stays the same."],
    ["Is this a guarantee for a sensitive photo?", "It removes metadata from the new file. If the picture itself shows something you don't want to share, crop or edit that separately."],
  ),
  "image-resizer": guide(
    "An image that's 4,000 pixels wide, resized to 800 with proportion locked, becomes 800 by whatever height keeps the same shape. Only unlock proportion if you mean to stretch it.",
    ["Where does the resize happen?", "Right in your browser, on a canvas. The file isn't uploaded."],
    ["What does keep proportion do?", "Height is calculated from the original aspect ratio. Turn it off and the height stays at the original pixel height."],
    ["Which format is the download?", "JPEG. If your image is transparent, it's drawn on white."],
    ["What do the social presets do?", "Instagram Reels, YouTube Shorts, and TikTok cover-crop to 1080×1920. LinkedIn banner cover-crops to 1584×396. Reels also shows a dashed safe-zone guide that isn't saved into the file."],
  ),
  "image-cropper": guide(
    "Set X 10, Y 10, width 80, height 80 and you'll keep the middle 80% of the photo, dropping a 10% margin on each side. Those values are percentages of the original.",
    ["How do the crop numbers work?", "X and Y are the top-left of your crop, as a percent of width and height. W and H are the size of the crop, also in percent."],
    ["Can the crop run off the edge?", "The rectangle is clamped so it stays inside the image."],
    ["Is the original file changed?", "No. You download a new image, and the source file stays put."],
  ),
  "jpg-to-png": guide(
    "Your JPEG is drawn onto a canvas and saved as PNG. The download comes out larger than the JPEG, because PNG doesn't use JPEG’s lossy compression.",
    ["Will this restore quality the JPEG lost?", "No. Pixels that were already compressed stay that way. The new file is just a PNG container for those pixels."],
    ["Does the PNG have transparency?", "No. A JPEG has no alpha channel, so your PNG is fully opaque."],
    ["Is the file uploaded?", "No. Conversion stays in your browser."],
  ),
  "png-to-jpg": guide(
    "A PNG logo on a transparent background becomes a JPEG on white. Photographic PNGs usually get much smaller — flat graphics can look a little softer.",
    ["What happens to transparency?", "JPEG can't store it. Transparent pixels are painted white before the file is saved."],
    ["Why would I convert to JPEG?", "Photos come out smaller as JPEG. Screenshots and logos with hard edges are often better left as PNG."],
    ["Can I choose the quality?", "This conversion uses a fixed high JPEG quality. Use the Image Compressor if you want a quality slider."],
  ),
  "webp-to-jpg": guide(
    "Your WebP photo is decoded by the browser, drawn on white, and saved as a JPEG you can open in older tools.",
    ["Why did my WebP fail?", "Your browser has to be able to decode it. An unusual WebP profile can fail even when a desktop app opens it."],
    ["Is animation kept?", "No. The image is drawn once and saved as a still JPEG."],
    ["Is the file uploaded?", "No. Decoding and saving happen locally, in your browser."],
  ),
  "svg-to-png": guide(
    "An SVG with its own width and height is drawn at that pixel size and saved as PNG. If width or height is missing, the browser can refuse the image.",
    ["Will the PNG be sharp on a retina screen?", "It uses the SVG’s own pixel size. Export the SVG larger if you need a bigger PNG."],
    ["Are fonts and external images included?", "Only if the browser can see them while drawing. External files and unloaded fonts may be missing."],
    ["Is the SVG uploaded?", "No. It's loaded locally into an image and drawn to a canvas."],
  ),
  "image-to-base64": guide(
    "A small PNG becomes a data URL that starts with data:image/png;base64, followed by the encoded bytes. Paste that into CSS or an img src and you're done.",
    ["Is Base64 smaller?", "No. It's about a third larger than the file. It's useful for embedding, not for saving space."],
    ["Should I embed a large photo this way?", "Usually no. A data URL of a big image makes the page heavier and harder to cache."],
    ["Does the file leave the browser?", "No. The FileReader builds the data URL locally."],
  ),
  "sankey-generator": guide(
    "Put Source, Target, and Value in a table — say Budget → Design 40 and Budget → Build 60 — and you'll get two ribbons whose thickness matches those values. Edit a number and the diagram updates.",
    ["What data shape does a Sankey need?", "Each row is a flow from one node to another, with a positive value. Nodes are created from the names you type."],
    ["Can I export the diagram?", "Yes. Export SVG if you want to edit it, or PNG for a slide. The export uses the colours and spacing currently on screen."],
    ["Why is a ribbon missing?", "A flow needs a source, a target, and a numeric value. Empty or zero rows are left out of the layout."],
  ),
  "colour-palette-generator": guide(
    "Start from #336699 and you'll get a small set of related swatches, built by shifting hue and lightness. Copy a hex when you want to use one.",
    ["How are the colours chosen?", "They're offsets from your starting colour, not a search of a brand library. Change the start colour and the set moves with it."],
    ["Can I lock a swatch?", "Not on this page. Copy the hex of a swatch you want to keep, then start again from that hex."],
    ["Does this check contrast?", "No. Use the Contrast Checker before you put a foreground and background together."],
  ),
  "contrast-checker": guide(
    "Black text on white is 21:1 and passes AA and AAA. Try white text on #767676 and you'll get about 4.6:1, which passes AA for normal text and fails AAA.",
    ["What ratios are the pass marks?", "AA normal text is 4.5:1, AA large text is 3:1, and AAA normal text is 7:1. These follow WCAG 2."],
    ["What counts as large text?", "WCAG treats 18pt regular, or 14pt bold, as large. This page reports both the normal and large thresholds."],
    ["Does a pass mean the design is accessible?", "Contrast is one requirement. Size, weight, and colour blindness still matter."],
  ),
  "gradient-generator": guide(
    "Two stops, #111111 to #ff0101, at 90 degrees, produce a CSS linear-gradient you can paste into a stylesheet. Add a stop if you want a colour in the middle.",
    ["Linear or radial?", "The control lets you switch. The copied CSS matches the type on screen."],
    ["How do I add a colour stop?", "Add a stop and set its hex and position. Positions are percentages along the gradient."],
    ["Will the CSS work in current browsers?", "Yes. linear-gradient and radial-gradient are standard CSS."],
  ),
  "colour-picker": guide(
    "#ff0101 is rgb(255, 1, 1). In HSL that's about 0° hue, 100% saturation, and 50% lightness. The swatch updates as you change the picker.",
    ["Which value should I copy into CSS?", "Hex is the usual choice. RGB is useful when you need to add an alpha channel yourself."],
    ["Does the picker include alpha?", "No. You get an opaque colour. Add the alpha in your stylesheet if you need transparency."],
    ["Is the HSL exact?", "It's converted from the hex. Rounding can move a channel by a fraction of a percent."],
  ),
  "hex-to-rgb": guide(
    "#ff0101 converts to 255, 1, 1. Type a three-digit hex such as #abc and it's expanded to #aabbcc before the channels are read.",
    ["Do I need the hash?", "You can type it with or without the leading #. The result is shown with one."],
    ["What if the hex is invalid?", "It needs 3 or 6 hexadecimal digits. An 8-digit hex that includes alpha isn't read."],
    ["Can I get HSL as well?", "Yes. The page shows hex, RGB, and HSL for the same colour."],
  ),
  "rgb-to-hex": guide(
    "Red 255, green 1, blue 1 becomes #ff0101. Channels above 255 are clamped, and decimals are rounded.",
    ["What range are the channels?", "0 to 255 for each of red, green, and blue."],
    ["How are the hex digits produced?", "Each channel is rounded, clamped, and written as two hexadecimal characters."],
    ["Does this accept an alpha channel?", "No. Add opacity in CSS if you need it, for example rgba() or an 8-digit hex you write yourself."],
  ),
  "favicon-generator": guide(
    "Drop the letter N on #111111 and you'll get a 64 pixel PNG with rounded corners and white type. Download it and reference it as a favicon, or drop it in a manifest.",
    ["What size is the file?", "64 by 64 pixels, PNG. Browsers will scale it. For a full icon set you may still want 32 and 180 pixel versions."],
    ["Can I use more than two characters?", "The field keeps two characters so they fit the tile."],
    ["Is this an ICO file?", "No. It's a PNG, which current browsers accept as a favicon."],
  ),
  "aspect-ratio-calculator": guide(
    "A 16:9 frame that's 1,920 pixels wide is 1,080 pixels tall. Enter both sides, 1920 and 1080, and the simplified ratio is 16:9.",
    ["How do I solve for a missing side?", "Fill the ratio and the side you know. Leave the unknown side blank."],
    ["How is a ratio simplified?", "The two pixel counts are divided by their greatest common divisor. 1920 and 1080 become 16 and 9."],
    ["Can I use centimetres instead of pixels?", "Yes. The maths is the same for any unit, as long as both sides use that unit."],
  ),
  "px-to-rem": guide(
    "16 pixels at a root size of 16 is 1 rem. 24 pixels at that root is 1.5 rem. If your root is 10 pixels, 16 pixels is 1.6 rem.",
    ["What is a rem?", "A rem is the root font size, usually the font-size on the html element. The default in most browsers is 16 pixels."],
    ["Should I change the root?", "Only if your stylesheet sets a different root font size. The converter divides pixels by the root you enter."],
    ["Is this the same as em?", "No. rem is always relative to the root. em is relative to the font size of the parent element."],
  ),
  "box-shadow-generator": guide(
    "X 0, Y 8, blur 24, spread 0, colour #111111 at 12% opacity produces box-shadow: 0px 8px 24px 0px rgba(17, 17, 17, 0.12). The preview square uses that same shadow.",
    ["What do the four lengths mean?", "X and Y move the shadow, blur softens it, and spread grows or shrinks it before the blur."],
    ["Can the shadow go up or left?", "Yes. Use a negative X or Y."],
    ["How is opacity applied?", "The colour is written as rgba. 12% opacity is an alpha of 0.12."],
  ),
  "border-radius-generator": guide(
    "A radius of 16 pixels copies as border-radius: 16px. The preview square shows you the same corner.",
    ["Can corners differ?", "This page sets one radius for every corner. Write the four-value CSS yourself if you need them to differ."],
    ["Pixels or percent?", "The control is in pixels, which is the usual unit for a component radius."],
    ["Does 9999 pixels make a pill?", "On a short element, a radius at least half the height makes a pill. Match the radius to the element’s size."],
  ),
  "funnel-chart": guide(
    "A marketing funnel of 8,200 visits, 1,640 sign-ups, 738 activated, 295 trials, and 88 paid shows each stage as a band, the percent remaining from the top, and the step conversion. Export PNG or SVG when it looks right.",
    ["How do I enter stages?", "Use the table: a name and a value per row. Paste from Excel if you already have the list. Add, duplicate, or reorder stages as you go."],
    ["What do the percentages mean?", "The figure on each stage is the share of the first stage. “Step” is the conversion from the stage above. Overall conversion is last divided by first."],
    ["What if a stage is larger than the one above?", "You’ll see a note. The band will widen — that’s honest, but it isn’t a conversion funnel any more."],
  ),
  "gantt-chart": guide(
    "A product launch with Brief, Design, Build, QA, and a Launch milestone shares one timeline. Drag a bar to move it; drag an end to change the duration. Today is the dashed line.",
    ["What date format is used?", "The date fields use YYYY-MM-DD. An end before the start is flagged on that row."],
    ["Can I show progress?", "Yes. Progress is a percent on the task. The bar fills by that amount."],
    ["Is this a full project planner?", "No. It’s a lightweight Gantt for a short plan you can export — not dependencies across a whole organisation."],
  ),
  "flowchart-generator": guide(
    "An approval flow — Request in, Review, Approved?, then Sign off or Revise — lays out automatically. Add a decision, connect Yes and No, and export.",
    ["How do I add a branch?", "Add a decision, choose Connect, then pick the next steps. The first link from a decision is labelled Yes, the next No — you can edit the label in the diagram."],
    ["Do I need graph syntax?", "No. Boxes and Connect are enough. Paste “From -> To” only if you already have a list of links."],
    ["Can I move boxes?", "Yes. Drag a box on the canvas. Fit resets the automatic layout."],
  ),
  "bar-chart-generator": guide(
    "Paste Product and Units — Apron 42, Barge 28, Valley 19 — and you get vertical bars, a zero baseline, and labels. Switch to horizontal or add a second series for a grouped chart.",
    ["How do I paste data?", "Copy a table from Excel or Sheets. The first column is the label; other numeric columns become series. CSV upload works the same way."],
    ["Can I stack series?", "Yes, when there’s more than one series. Grouped and stacked both sit under Customize."],
    ["How do I export?", "Use Export for PNG, SVG, a copy of the image, or the data as CSV."],
  ),
  "line-chart-generator": guide(
    "Monthly revenue for 2025 and 2026 plots two lines on one chart. If the values sit in a narrow band, the vertical axis doesn’t have to start at zero — turn that on if you want it.",
    ["What does each row need?", "A label (a month or a date) and a number per series. Paste a table and the columns are mapped for you."],
    ["Can I plot more than one series?", "Yes. Name the series at the top of the table, or paste extra numeric columns."],
    ["Why doesn’t the axis always start at zero?", "A line of temperatures or index values is easier to read without a long empty stretch. The control is labelled Start axis at zero."],
  ),
  "pie-chart-generator": guide(
    "Search 46, Direct 22, Referral 16, Email 10, and Social 6 make a pie of those parts. Switch to a donut if you want the centre clear for a total.",
    ["Do the values have to add up to 100?", "No. Each slice is its share of the total of the values you enter."],
    ["What happens to a negative?", "It can’t be a slice. It’s left out of the pie and called out above the chart, so it isn’t silently zeroed."],
    ["How many slices stay readable?", "About seven. More than that, and you’ll see a note suggesting a bar chart or grouping the small ones."],
  ),
  "timeline-generator": guide(
    "Q1 2026 Kick-off, March 2026 Private beta, 10 June 2026 Public launch stacks on a vertical line, earliest first. Switch to horizontal if you’d rather read left to right.",
    ["What dates work?", "A year, a quarter, a month, or a day: 2026, Q1 2026, March 2026, or 10 March 2026."],
    ["Are events sorted?", "By date, unless you choose As entered under Customize."],
    ["Can I add a category?", "Yes. Categories tint the markers so related events group visually."],
  ),
  "diagram-generator": guide(
    "Brief → Design → Build → Review lays out as connected boxes. Drag to place, add a box, connect it, export PNG or SVG.",
    ["How do I add a connection?", "Select Connect on a box, then pick the target. Arrow direction follows that order."],
    ["Can I paste From -> To?", "Yes — that’s an optional advanced input, not the main way to build."],
    ["Is this a layout engine?", "It’s a light automatic layout with drag. For quantities flowing between nodes, use the Sankey generator."],
  ),
}
