import { guide, type ToolGuideCopy } from "@/lib/tools/guides/types"

export const filesDesignVizGuides: Record<string, ToolGuideCopy> = {
  "image-compressor": guide(
    "A 4 MB photo, saved again as a JPEG at about 70% quality and no edge longer than 2,400 pixels, often lands well under 1 MB. The original file is not changed.",
    ["Is the image uploaded?", "No. It is redrawn on a canvas in your browser and offered as a download."],
    ["Why is the result a JPEG?", "The compressor saves JPEG so the quality slider can shrink the file. Transparency is flattened onto white."],
    ["Will this hurt print quality?", "Large prints want the original. The size cap and the quality slider are meant for screens and the web."],
  ),
  "exif-stripper": guide(
    "A phone photo can carry GPS coordinates in its EXIF. Redrawing it as a new JPEG drops that metadata. The download is a new file, and the original stays where it was.",
    ["What is removed?", "Anything that lived in the file metadata, including camera model and location, because the pixels are copied onto a fresh canvas and saved again."],
    ["Does the picture look the same?", "It is saved as a high-quality JPEG, so you may see a small compression change. The framing stays the same."],
    ["Is this a guarantee for a sensitive photo?", "It removes metadata from the new file. Crop or edit separately if the picture itself shows something you do not want to share."],
  ),
  "image-resizer": guide(
    "An image that is 4,000 pixels wide, resized to 800 with proportion locked, becomes 800 by whatever height keeps the same shape. Unlock proportion only when you mean to stretch it.",
    ["Where does the resize happen?", "In the browser, on a canvas. The file is not uploaded."],
    ["What does keep proportion do?", "Height is calculated from the original aspect ratio. Turn it off and the height stays at the original pixel height."],
    ["Which format is the download?", "JPEG. A transparent image is drawn on white."],
    ["What do the social presets do?", "Instagram Reels, YouTube Shorts, and TikTok cover-crop to 1080×1920. LinkedIn banner cover-crops to 1584×396. Reels also shows a dashed safe-zone guide that is not saved into the file."],
  ),
  "image-cropper": guide(
    "X 10, Y 10, width 80, height 80 keeps the middle 80% of the photo and drops a 10% margin on each side. The values are percentages of the original.",
    ["How do the crop numbers work?", "X and Y are the top-left of the crop, as a percent of width and height. W and H are the size of the crop, also in percent."],
    ["Can the crop run off the edge?", "The rectangle is clamped so it stays inside the image."],
    ["Is the original file changed?", "No. You download a new image. The source file stays put."],
  ),
  "jpg-to-png": guide(
    "A JPEG is drawn onto a canvas and saved as PNG. The download is larger than the JPEG, because PNG does not use JPEG’s lossy compression.",
    ["Will this restore quality the JPEG lost?", "No. Pixels that were already compressed stay that way. The new file is just a PNG container for those pixels."],
    ["Does the PNG have transparency?", "No. A JPEG has no alpha channel, so the PNG is fully opaque."],
    ["Is the file uploaded?", "No. Conversion stays in the browser."],
  ),
  "png-to-jpg": guide(
    "A PNG logo on a transparent background becomes a JPEG on white. Photographic PNGs usually get much smaller. Flat graphics can look softer.",
    ["What happens to transparency?", "JPEG cannot store it. Transparent pixels are painted white before the file is saved."],
    ["Why would I convert to JPEG?", "Photos are smaller as JPEG. Screenshots and logos with hard edges are often better left as PNG."],
    ["Can I choose the quality?", "This conversion uses a fixed high JPEG quality. Use the Image Compressor if you want a quality slider."],
  ),
  "webp-to-jpg": guide(
    "A WebP photo is decoded by the browser, drawn on white, and saved as a JPEG you can open in older tools.",
    ["Why did my WebP fail?", "The browser has to be able to decode it. An unusual WebP profile can fail even when a desktop app opens it."],
    ["Is animation kept?", "No. The image is drawn once and saved as a still JPEG."],
    ["Is the file uploaded?", "No. Decoding and saving happen locally."],
  ),
  "svg-to-png": guide(
    "An SVG with its own width and height is drawn at that pixel size and saved as PNG. A missing width or height can make the browser refuse the image.",
    ["Will the PNG be sharp on a retina screen?", "It uses the SVG’s own pixel size. Export the SVG larger if you need a bigger PNG."],
    ["Are fonts and external images included?", "Only if the browser can see them while drawing. External files and unloaded fonts may be missing."],
    ["Is the SVG uploaded?", "No. It is loaded locally into an image and drawn to a canvas."],
  ),
  "image-to-base64": guide(
    "A small PNG becomes a data URL that starts with data:image/png;base64, followed by the encoded bytes. You can paste that into CSS or an img src.",
    ["Is Base64 smaller?", "No. It is about a third larger than the file. It is useful for embedding, not for saving space."],
    ["Should I embed a large photo this way?", "Usually no. A data URL of a big image makes the page heavier and harder to cache."],
    ["Does the file leave the browser?", "No. The FileReader builds the data URL locally."],
  ),
  "sankey-generator": guide(
    "A table of Source, Target, and Value, such as Budget → Design 40 and Budget → Build 60, draws two ribbons whose thickness matches those values. Edit a number and the diagram updates.",
    ["What data shape does a Sankey need?", "Each row is a flow from one node to another, with a positive value. Nodes are created from the names you type."],
    ["Can I export the diagram?", "Yes. Export SVG for editing, or PNG for a slide. The export uses the colours and spacing currently on screen."],
    ["Why is a ribbon missing?", "A flow needs a source, a target, and a numeric value. Empty or zero rows are left out of the layout."],
  ),
  "colour-palette-generator": guide(
    "Start from #336699 and the generator builds a small set of related swatches by shifting hue and lightness. Copy a hex when you want to use one.",
    ["How are the colours chosen?", "They are offsets from your starting colour, not a search of a brand library. Change the start colour and the set moves with it."],
    ["Can I lock a swatch?", "Not on this page. Copy the hex of a swatch you want to keep, then start again from that hex."],
    ["Does this check contrast?", "No. Use the Contrast Checker before you put a foreground and background together."],
  ),
  "contrast-checker": guide(
    "Black text on white is 21:1 and passes AA and AAA. White text on #767676 is about 4.6:1, which passes AA for normal text and fails AAA.",
    ["What ratios are the pass marks?", "AA normal text is 4.5:1, AA large text is 3:1, and AAA normal text is 7:1. These follow WCAG 2."],
    ["What counts as large text?", "WCAG treats 18pt regular, or 14pt bold, as large. This page reports both the normal and large thresholds."],
    ["Does a pass mean the design is accessible?", "Contrast is one requirement. Size, weight, and colour blindness still matter."],
  ),
  "gradient-generator": guide(
    "Two stops, #111111 to #ff0101, at 90 degrees, produce a CSS linear-gradient you can paste into a stylesheet. Add a stop to put a colour in the middle.",
    ["Linear or radial?", "The control lets you switch. The copied CSS matches the type on screen."],
    ["How do I add a colour stop?", "Add a stop and set its hex and position. Positions are percentages along the gradient."],
    ["Will the CSS work in current browsers?", "Yes. linear-gradient and radial-gradient are standard CSS."],
  ),
  "colour-picker": guide(
    "#ff0101 is rgb(255, 1, 1). In HSL that is about 0° hue, 100% saturation, and 50% lightness. The swatch updates as you change the picker.",
    ["Which value should I copy into CSS?", "Hex is the usual choice. RGB is useful when you need to add an alpha channel yourself."],
    ["Does the picker include alpha?", "No. You get an opaque colour. Add the alpha in your stylesheet if you need transparency."],
    ["Is the HSL exact?", "It is converted from the hex. Rounding can move a channel by a fraction of a percent."],
  ),
  "hex-to-rgb": guide(
    "#ff0101 converts to 255, 1, 1. A three-digit hex such as #abc is expanded to #aabbcc before the channels are read.",
    ["Do I need the hash?", "You can type it with or without the leading #. The result is shown with one."],
    ["What if the hex is invalid?", "It needs 3 or 6 hexadecimal digits. An 8-digit hex that includes alpha is not read."],
    ["Can I get HSL as well?", "Yes. The page shows hex, RGB, and HSL for the same colour."],
  ),
  "rgb-to-hex": guide(
    "Red 255, green 1, blue 1 becomes #ff0101. Channels above 255 are clamped, and decimals are rounded.",
    ["What range are the channels?", "0 to 255 for each of red, green, and blue."],
    ["How are the hex digits produced?", "Each channel is rounded, clamped, and written as two hexadecimal characters."],
    ["Does this accept an alpha channel?", "No. Add opacity in CSS if you need it, for example rgba() or an 8-digit hex you write yourself."],
  ),
  "favicon-generator": guide(
    "The letter N on #111111 draws a 64 pixel PNG with rounded corners and white type. Download it and reference it as a favicon, or drop it in a manifest.",
    ["What size is the file?", "64 by 64 pixels, PNG. Browsers will scale it. For a full icon set you may still want 32 and 180 pixel versions."],
    ["Can I use more than two characters?", "The field keeps two characters so they fit the tile."],
    ["Is this an ICO file?", "No. It is a PNG, which current browsers accept as a favicon."],
  ),
  "aspect-ratio-calculator": guide(
    "A 16:9 frame that is 1,920 pixels wide is 1,080 pixels tall. Enter both sides, 1920 and 1080, and the simplified ratio is 16:9.",
    ["How do I solve for a missing side?", "Fill the ratio and the side you know. Leave the unknown side blank."],
    ["How is a ratio simplified?", "The two pixel counts are divided by their greatest common divisor. 1920 and 1080 become 16 and 9."],
    ["Can I use centimetres instead of pixels?", "Yes. The maths is the same for any unit, as long as both sides use that unit."],
  ),
  "px-to-rem": guide(
    "16 pixels at a root size of 16 is 1 rem. 24 pixels at that root is 1.5 rem. If the root is 10 pixels, 16 pixels is 1.6 rem.",
    ["What is a rem?", "A rem is the root font size, usually the font-size on the html element. The default in most browsers is 16 pixels."],
    ["Should I change the root?", "Only if your stylesheet sets a different root font size. The converter divides pixels by the root you enter."],
    ["Is this the same as em?", "No. rem is always relative to the root. em is relative to the font size of the parent element."],
  ),
  "box-shadow-generator": guide(
    "X 0, Y 8, blur 24, spread 0, colour #111111 at 12% opacity produces box-shadow: 0px 8px 24px 0px rgba(17, 17, 17, 0.12). The preview square uses that shadow.",
    ["What do the four lengths mean?", "X and Y move the shadow, blur softens it, and spread grows or shrinks it before the blur."],
    ["Can the shadow go up or left?", "Yes. Use a negative X or Y."],
    ["How is opacity applied?", "The colour is written as rgba. 12% opacity is an alpha of 0.12."],
  ),
  "border-radius-generator": guide(
    "A radius of 16 pixels copies as border-radius: 16px. The preview square shows the same corner.",
    ["Can corners differ?", "This page sets one radius for every corner. Write the four-value CSS yourself if you need them to differ."],
    ["Pixels or percent?", "The control is in pixels, which is the usual unit for a component radius."],
    ["Does 9999 pixels make a pill?", "On a short element, a radius at least half the height makes a pill. Match the radius to the element’s size."],
  ),
  "funnel-chart": guide(
    "Stages of 1,000 visits, 400 signups, and 80 purchases draw three bars. Each stage also shows the percent remaining from the top and the drop from the stage above.",
    ["How should I enter the stages?", "One stage a line, largest at the top if it is a real funnel. The chart does not sort them."],
    ["What is the drop percentage?", "The difference from the previous stage, divided by that previous stage. The first stage has no drop."],
    ["Can values go up?", "Yes, but then it is no longer a funnel. The bars will grow instead of shrink."],
  ),
  "gantt-chart": guide(
    "A task from 1 October to 14 October, and another from 10 October to 5 November, share one timeline. The bars sit on the days you type.",
    ["What date format is used?", "YYYY-MM-DD. An end date before the start date will not draw a useful bar."],
    ["Can tasks overlap?", "Yes. Each task is its own row, so overlapping dates are easy to see."],
    ["Does this schedule resources?", "No. It is a simple timeline of named tasks, not a dependency or staffing plan."],
  ),
  "flowchart-generator": guide(
    "Three lines — Collect the numbers, Check the edge cases, Ship the tool — become three boxes with a connector between each. Order is the order of the lines.",
    ["How do I add a step?", "Put each step on its own line. Blank lines are skipped."],
    ["Can I branch?", "Not on this page. It is a single sequence. Use the Diagram Generator for arrows between named nodes."],
    ["Can I export it?", "Copy is not built in. Screenshot the chart, or rebuild a complex flow in a diagram tool."],
  ),
  "bar-chart-generator": guide(
    "Design 12, Build 18, and Review 7 draw three bars. Build is the longest because 18 is the maximum. Each row is a label, then a number.",
    ["How do I separate the label and the value?", "A comma is the clearest separator: Design, 12. A colon or space before the number also works."],
    ["Do the bars start at zero?", "The scale starts at zero when every value is positive. A negative value is drawn, but the track is sized from the largest value."],
    ["Can I use this for time series?", "You can, with the period as the label. A line chart is usually easier to read for a sequence."],
  ),
  "line-chart-generator": guide(
    "Mon 4, Tue 6, Wed 5, Thu 9 plots four points and joins them. The vertical scale runs from the smallest value to the largest.",
    ["What does each line need?", "A label and a number, separated by a comma. The points are plotted in the order you type them."],
    ["Can I plot more than one series?", "No. This page draws one line. Put a second series in a second chart."],
    ["Are the axes labelled with units?", "The horizontal labels are the text you type. Add the unit in the label if you need it, such as Mon (hrs)."],
  ),
  "pie-chart-generator": guide(
    "Search 40, Direct 25, and Email 15 make a pie of 80 parts. Search is half the circle, because 40 is half of 80.",
    ["Do the values have to add up to 100?", "No. Each slice is its share of the total of the values you enter."],
    ["What happens to a zero or a negative?", "Negatives are treated as zero for the slice. A zero adds no angle."],
    ["How many slices are readable?", "A handful. More than about six slices, and the legend becomes the useful part."],
  ),
  "timeline-generator": guide(
    "2026-01 — First sketch, then 2026-04 — Private beta, then 2026-10 — Public tools, stacks three events on a vertical line. The em dash separates the date from the note.",
    ["How do I split the date and the note?", "Type an em dash or a hyphen-minus between them. The text before the dash is the label, and the rest is the note."],
    ["Are the events sorted?", "No. They stay in the order you type, so put the earliest first if you want a chronology."],
    ["Can I use a season instead of a date?", "Yes. The label is plain text, so “Autumn 2026” works as well as a calendar date."],
  ),
  "diagram-generator": guide(
    "Brief -> Design, Design -> Build, and Build -> Review draw three arrows. The same name on two lines is the same node, so Design connects onward to Build.",
    ["How do I write a link?", "From, then ->, then to. One link a line. Spaces around the arrow are optional."],
    ["Can a node have two outgoing arrows?", "Yes. Write two lines that start with the same name."],
    ["Is this a layout engine?", "It is a simple list of arrows, not an automatic graph layout. For a flow of quantities, use the Sankey generator."],
  ),
}
