import { guide, type ToolGuideCopy } from "@/lib/tools/guides/types"

export const homePeopleTextGuides: Record<string, ToolGuideCopy> = {
  "paint-calculator": guide(
    "A 3.5 m by 4 m room, 2.4 m high, two coats at 10 m²/L, no openings, ceiling included, is 50 m². That is 10.0 L of paint. Tins come in 1, 2, 4, 10, and 15 L, so the suggested purchase is 1 × 10 L.",
    ["How much paint do I need?", "Enter the room, the coats, and the coverage on the tin. The result is litres, then a tin combination you can actually buy."],
    ["Does it include the ceiling?", "Only when the ceiling box is ticked. Walls are included either way."],
    ["How are doors and windows counted?", "In the precise mode: each door is 1.8 m², each window 1.2 m². Add extra area for a large slider."],
    ["Should I buy the exact litres?", "No. Paint is sold in tins. The calculator shows the calculated litres and a suggested pack that covers it."],
    ["Why isn’t coverage exact?", "It varies by surface, paint, and how you apply it. Use the figure on the tin. 10 m²/L is a conservative starting point."],
  ),
  "material-estimator": guide(
    "A 6 m by 2.7 m plasterboard wall, with 10% waste, is 7 sheets of 2400 × 1200 mm. Studs along 4.8 m at 450 mm centres are 12 studs, counting both ends. A 4 m × 3 m floor at 2.4 m² a pack, with 10% waste, is 6 packs.",
    ["Which materials can I estimate?", "Plasterboard sheets, timber studs at a spacing you set, or flooring packs from the coverage on the carton."],
    ["Is waste included?", "Plasterboard and flooring include the waste percent you set (10% by default). Studs are a count of centres plus both ends, with optional extras for openings."],
    ["Are these order quantities?", "They’re a ballpark from the measurements. Openings, corners, and offcuts on site will change the real order. Confirm pack sizes at the supplier."],
  ),
  "concrete-calculator": guide(
    "A slab 4 m by 3 m by 100 mm is 1.2 m³. With 5% waste that’s 1.26 m³. A truck is usually ordered in 0.2 m³ steps, so 1.4 m³. At about 0.01 m³ per 20 kg bag, that’s 126 bags.",
    ["How is the volume calculated?", "Length × width × depth. Depth is millimetres by default — type 100 for a 100 mm slab, not 0.1."],
    ["How many bags are in a cubic metre?", "This page uses 0.01 m³ per 20 kg bag, so 100 bags per cubic metre, rounded up after waste."],
    ["Is this ready-mix or bagged concrete?", "The cubic metres suit either. The bag count is for pre-mix bags. If you order a truck, use the rounded cubic metres."],
  ),
  "gravel-calculator": guide(
    "A path 6 m by 2 m, 50 mm deep, is 0.6 m³. With 10% waste that’s 0.66 m³. At 1.5 tonnes per cubic metre, that’s about 1.0 t — handy to know before you ring the yard.",
    ["Why 1.5 tonnes per cubic metre?", "It’s a typical loose-gravel density. Wet or compacted gravel can be heavier. Ask the supplier if the rate differs."],
    ["What units are the measurements?", "Length and width default to metres. Depth defaults to millimetres, so 50 mm is 50, not 0.05 m."],
    ["Does this include compaction?", "Not as a separate step. If the gravel will settle, keep a waste allowance on."],
  ),
  "mulch-calculator": guide(
    "A bed 5 m by 1.2 m, 70 mm deep, is 0.42 m³. With 5% waste that’s about 0.44 m³, or 441 litres — about 18 bags of 25 L.",
    ["How deep should mulch be?", "Around 50 to 75 mm is a common garden depth. Type the depth in millimetres."],
    ["How do I convert to bags?", "The page shows 25 L bags. Divide the litres by the bag you actually buy if it differs."],
    ["Are the measurements in metres?", "Length and width are. Depth is millimetres by default."],
  ),
  "roof-pitch-calculator": guide(
    "A rise of 300 mm over a run of 1,000 mm is a pitch of about 16.7 degrees. The rafter along that triangle is about 1,044 mm, and the slope factor is 1.044 — once you have that, plan lengths turn into sloped lengths.",
    ["What are rise and run?", "Rise is the vertical height. Run is the horizontal distance. You can type millimetres, metres, or feet."],
    ["What is the slope factor?", "Rafter length divided by run. Multiply a plan length by the factor to get the sloped length."],
    ["Is this a structural design?", "No. It’s the geometry of the triangle. Check spans and members separately."],
  ),
  "tile-calculator": guide(
    "A room 4.2 m by 3.1 m is 13.02 m². A 600 mm square tile covers 0.36 m². With 10% waste, you need 40 tiles — better a few spare than a short box.",
    ["Can the tiles be rectangular?", "Yes. Enter length and width separately."],
    ["What does waste cover?", "Cuts, breakages, and a spare. 10% is common. Use 15–20% for a diagonal lay."],
    ["Does this subtract cupboards?", "No. Measure the floor you will actually tile."],
  ),
  "drywall-calculator": guide(
    "A wall 6 m long and 2.7 m high is 16.2 m². With 10% waste that’s 17.8 m². A 2400 × 1200 mm sheet covers 2.88 m², so you need 7 sheets.",
    ["Which sheet size is assumed?", "2400 by 1200 mm, the common plasterboard sheet."],
    ["Does this include waste?", "Yes — the percent you set, 10% by default, then rounded up to a whole sheet."],
    ["Are both sides of a wall included?", "Only if you enter the combined length. Length times height is one face."],
  ),
  "fence-calculator": guide(
    "An 18 m run with posts every 2.4 m needs 9 posts, counting both ends. Two rail rows need 16 rails, because there are 8 bays.",
    ["Does the post count include the ends?", "Yes. It’s the number of bays, plus one, so a leftover length still gets an end post."],
    ["What is a rail row?", "A horizontal rail. Two rows means two rails on every bay."],
    ["Are palings included?", "No. This page counts posts and rails only."],
  ),
  "deck-calculator": guide(
    "A deck 4.8 m by 3.6 m, with 90 mm boards and a 5 mm gap, needs 38 boards across the width. With 10% waste that’s 42 boards, each 4.8 m — about 202 m of decking.",
    ["Which way do the boards run?", "Along the length you enter. The width is divided by the board width plus the gap."],
    ["Should I add waste?", "Yes if you expect cuts around posts. 10% is the default; set it to none if you don’t want it."],
    ["Are joists included?", "No. This is the decking boards only."],
  ),
  "paver-calculator": guide(
    "24 m² of 200 by 100 mm pavers, with 10% waste, is 1,320 pavers. Each paver covers 0.02 m² before the waste is added.",
    ["How is waste applied?", "The area is increased by the percent, then divided by the paver face and rounded up."],
    ["What about joint gaps?", "They aren’t subtracted. If the joints are wide, the real count is a little lower."],
    ["Can the pavers be rectangular?", "Yes. Enter length and width separately, in millimetres."],
  ),
  "roofing-calculator": guide(
    "A plan area of 80 m² with a rise of 300 mm over a run of 1,000 mm has a slope factor of about 1.044. The roof area is about 83.5 m². With 10% waste, order about 91.9 m².",
    ["What is plan area?", "The flat footprint of the roof, not the sloped surface. The pitch stretches it into the real roof area."],
    ["Does this include eaves?", "Only if they are inside the plan area you enter."],
    ["Is this the area to order?", "The sloped area is the true roof. Add waste for hips, valleys, and ridge before you order sheets or tiles."],
  ),
  "roofing-shingle-calculator": guide(
    "90 m² of roof at 3 m² a bundle, with 10% waste, is 33 bundles. Change the cover per bundle to match the product label.",
    ["What is a bundle?", "A pack of shingles. Coverage per bundle is printed on the wrapping. Three square metres is the default here, not a standard you should assume."],
    ["Does this include starter strips and ridge?", "No. Order those from the manufacturer’s instructions, on top of the field bundles."],
    ["Should I add waste?", "Yes for hips and valleys. 10% is the default."],
  ),
  "gutter-calculator": guide(
    "22 metres of gutter, with a downpipe every 8 metres, needs 3 downpipes. The gutter length is the length you type.",
    ["Why one downpipe per 8 metres?", "It’s a rough spacing guide. Local rules and rainfall can ask for closer spacing."],
    ["Are corners and stop ends included?", "No. Count corners, outlets, and stop ends from the plan."],
    ["What length should I enter?", "The total run of gutter, in metres, including each side of the building you are guttering."],
  ),
  "hvac-btu-calculator": guide(
    "A 40 m² room at about 430 BTU per square metre needs about 17,200 BTU/h, which is about 5.0 kW. A sensible band is about 4.3–5.8 kW. That is a rough screen, not a heat load.",
    ["Where does 430 BTU per square metre come from?", "It is a rule of thumb from about 40 BTU per square foot. Real loads depend on glass, insulation, and climate."],
    ["How do you convert BTU/h to kW?", "Divide by 3,412."],
    ["Can I size a unit from this alone?", "No. Use it to get in the right range, then have the system sized properly."],
  ),
  "board-foot-calculator": guide(
    "Eight pieces, 25 mm thick, 150 mm wide, and 2.4 m long, are about 30.5 board feet, or about 0.072 m³. Thickness and width are millimetres, length is metres.",
    ["What is a board foot?", "A volume of 12 × 12 × 1 inch. The formula is thickness in inches × width in inches × length in feet, divided by 12."],
    ["Why mix millimetres and board feet?", "Timber in Australia is often measured in millimetres, while board feet are still used in some price lists. The page converts for you."],
    ["Does it include waste?", "No. Multiply by the number of pieces you will cut from, not the finished count, if offcuts matter."],
  ),
  "stair-stringer-calculator": guide(
    "A total rise of 2,700 mm with a target riser of 175 mm gives 15 risers of 180 mm and 14 treads. At a 250 mm going, 2R+G is 610 mm — outside the 700–750 mm band many Australian guides use — and the stringer is about 4.62 m.",
    ["How is the number of risers chosen?", "Total rise divided by the target riser, rounded to the nearest whole number, and at least one."],
    ["What is 2R+G?", "Two risers plus one going. Many Australian stair guides look for 700–750 mm. This page reports the number; it does not pass or fail the stair."],
    ["Does this meet the building code?", "No. Riser and going limits differ by place. Check the numbers against the code that applies to the stair."],
  ),
  "stud-wall-calculator": guide(
    "A 4.8 m wall at 450 mm centres needs 12 studs, counting both ends. The old “length divided by spacing, rounded down, plus one” can miss the end stud when the length isn’t an exact multiple.",
    ["Does this include plates and noggins?", "No. It’s the vertical studs only."],
    ["Should the spacing be 450 or 600?", "450 mm is the default. Use the spacing the sheet size and the load require."],
    ["Are corners and openings extra?", "Yes. Use the extra-studs field for junctions, doors, and windows."],
  ),
  "construction-estimate-generator": guide(
    "Demolition $800, framing $2,400, and fixing $1,600 total $4,800. At a 15% markup the markup is $720 and the price is $5,520 — cost plus the percent you add on top.",
    ["How do I write a line?", "A name, then the amount, such as Framing, 2400. One cost a line."],
    ["Is the markup markup or margin?", "It is a percent added on top of cost. 15% of $4,800 is added to the cost. It is not 15% of the final price."],
    ["Can I send this as a quote?", "Copy the summary for a working total. Use Quote Builder if you need a document to send."],
  ),
  "work-style": guide(
    "Five answers that lean maker land on Maker. The page says you tend to reach for the work itself, and offers a question to take to the team: where do you need uninterrupted time this week? A 3–1–1–0 mix is shown as counts, not a hidden score.",
    ["Is this a personality test?", "No. It is a conversation starter. It does not diagnose, certify, or tell you who to hire."],
    ["What if two styles tie?", "Both are shown. Most people are a mix — the page will not pick a single winner."],
    ["Are the answers stored?", "Only in this browser tab, so you can refresh and go back. They are not sent anywhere. Start again to clear them."],
    ["Can I share the result?", "Yes. Copy or download the text. It is written as “you tend to…”, not as a type."],
  ),
  "meeting-cost": guide(
    "Six people at $85 an hour, meeting for 45 minutes, four times a month, cost $382.50 a sitting. That is $1,530 a month, and $18,360 a year — about 216 hours of people’s time. The yearly figure is the one that usually lands.",
    ["How is the cost calculated?", "People × hourly rate × length of one meeting. The month multiplies by how often it repeats. The year is that month times 12."],
    ["Should I use salary or charge-out rate?", "Use the rate that matches the decision. Charge-out shows client cost. Salary shows payroll cost, and still ignores overhead."],
    ["Does this include preparation?", "Only if you add that time to the meeting length."],
  ),
  "raci-generator": guide(
    "A task “Publish the page” with Alex as R, Sam as A, and Priya as C reads Responsible, Accountable, Consulted. The page warns if a task has no accountable person, or more than one. Copy exports the grid as tab-separated text for a spreadsheet.",
    ["What do R, A, C, and I mean?", "Responsible does the work. Accountable owns the outcome — usually one person. Consulted is asked. Informed is told."],
    ["How many A’s should a task have?", "One. More than one accountable and nobody is. The page will say so under the task."],
    ["Can I paste the grid into a spreadsheet?", "Yes. Copy table is tab-separated. Download .csv if you would rather have a file."],
  ),
  "team-working-agreement": guide(
    "A team named Studio, overlap hours of 10:00–15:00, a same-day response for blockers, and a sentence on how decisions are made, becomes a one-page agreement you can copy.",
    ["What is a working agreement?", "A short list of how the team will behave: hours, response, and decisions. It is not an employment contract."],
    ["How long should each answer be?", "One or two sentences. The page prints them under plain headings."],
    ["Can we revise it?", "Yes. Change the fields and copy again. Agreements are useful when the team updates them."],
  ),
  "meeting-agenda": guide(
    "“Weekly studio” on Monday at 10:00, with three items, becomes a numbered agenda. Each line in the items box is one numbered point.",
    ["How do I add an item?", "One item a line. Blank lines are skipped."],
    ["Can I add times?", "Put the time in the item text, such as “10:05 What shipped”. The page doesn’t calculate a timetable."],
    ["Does this invite anyone?", "No. Copy the agenda into the calendar invite yourself."],
  ),
  "one-on-one-agenda": guide(
    "A 1:1 with a name, a note on what happened, a blocker, and an action, becomes three short sections. Empty sections still appear, marked with a dash, so you can see what’s still to fill in.",
    ["What belongs in a 1:1 agenda?", "What changed since last time, what is stuck, and what you will do next. Keep it short enough to talk through."],
    ["Who fills it in?", "Either person. The page doesn’t assign fields to a manager or a report."],
    ["Is the note private?", "It stays in the browser. Copy it into your own notes if it should be kept. Closing the tab clears it."],
  ),
  "team-icebreaker": guide(
    "Each click draws one prompt, such as “What is a small thing that made today better?”. The list is a fixed set of light questions. The same prompt will not come back until the others have had a turn.",
    ["Are the prompts appropriate for work?", "They’re written for a team meeting. They avoid personal topics."],
    ["Can I add our own prompts?", "Not on this page. The list is built in. Use the Random Choice Picker if you want to supply the lines."],
    ["Will the same prompt repeat?", "Not immediately. Once every prompt has been drawn, the bag starts again."],
  ),
  "word-counter": guide(
    "“Nice Build is a quiet place for useful tools.” is 9 words, 45 characters, 37 without spaces, 1 sentence, and about 3 seconds to read at 200 words a minute. Select a few words in the box to count only the selection.",
    ["How are words counted?", "The trimmed text is split on whitespace. A hyphenated word counts as one."],
    ["How is reading time calculated?", "Words divided by 200 words a minute, shown as minutes and seconds. Nine words is 3 seconds, not a rounded minute."],
    ["Do line breaks count as characters?", "Yes. Every character in the box is counted, including spaces and new lines. “Without spaces” removes all whitespace."],
    ["Does any of this leave my browser?", "No. Your text stays on your device."],
  ),
  "diff-checker": guide(
    "Original “The quiet toolkit. / Built nicely.” against “The quiet toolkit. / Built carefully.” keeps the first line, marks the old second line as removed, and the new one as added. Swap sides if you pasted them the wrong way around.",
    ["Line or word compare?", "Lines is the default — a one-word change marks the whole line. Words highlights the tokens that actually moved."],
    ["What if the texts are very long?", "Very large pairs are summarised instead of fully compared, so the page stays responsive. Split a huge document into sections."],
    ["Can I copy the result?", "Yes. Copy diff gives a unified-style listing you can paste into a review."],
    ["Does any of this leave my browser?", "No. Your text stays on your device."],
  ),
  "case-converter": guide(
    "“the quiet toolkit for everyday work” becomes “The quiet toolkit for everyday work” in sentence case, “The Quiet Toolkit for Everyday Work” in title case (small words stay lowercase), and “theQuietToolkitForEverydayWork” in camelCase.",
    ["How does title case treat small words?", "Words such as a, an, the, and, or, of, to, in, on, for, but, nor, as, at, by, and vs stay lowercase unless they are the first or last word."],
    ["What is sentence case?", "The first letter of the text is capitalised, and so is the first letter after a full stop, question mark, or exclamation mark. The rest is lowercase."],
    ["What about camelCase and snake_case?", "Those modes split the text into words, then join them as an identifier. Punctuation is dropped."],
    ["Does it change punctuation?", "Sentence, title, upper, and lower leave punctuation in place. Identifier modes drop it."],
  ),
  "character-counter": guide(
    "“Nice Build” is 10 characters, 9 without spaces, 1 line, and 10 UTF-8 bytes. A second line makes the line count 2, and the newline is a character too.",
    ["Are spaces counted?", "The first number includes them. “Without spaces” removes every whitespace character."],
    ["Do emoji count as one character?", "The character count uses JavaScript string length (UTF-16 code units), so some emoji count as two. UTF-8 bytes is the encoded size."],
    ["Is this the same as the word counter?", "The word counter also shows words, sentences, and reading time. This page is the character counts, including UTF-8 bytes."],
  ),
  "readability-checker": guide(
    "“The cat sat on the mat.” scores as easy on the Flesch scale, because the words and the sentence are short. A long sentence of long words scores harder.",
    ["What is Flesch reading ease?", "A number from the count of words, sentences, and syllables. Higher is easier. Around 60 to 70 is plain English."],
    ["How are syllables counted?", "Vowel groups in each word, with a silent trailing e removed when that still leaves a syllable. It’s an estimate."],
    ["Does a high score mean the writing is good?", "It means the surface is easy to read. It doesn’t check whether the facts are right."],
  ),
  "reading-time": guide(
    "Forty-four words at 220 words a minute is about 12 seconds. The default pace is 220. A technical text is often closer to 180.",
    ["What pace should I use?", "220 suits everyday prose. Use 180 for dense text, or the pace your audience actually reads at."],
    ["Are headings counted?", "Yes, if they are in the box. The count is every whitespace-separated word."],
    ["Does this include looking at images?", "No. It’s words divided by pace, nothing else."],
  ),
  "lorem-ipsum": guide(
    "Three paragraphs produce three blocks of placeholder Latin, each a different length. The text is fixed for a given count, so a layout doesn’t jump between reloads.",
    ["Is this real Latin?", "It’s the familiar lorem ipsum filler. It isn’t meant to be translated."],
    ["Why is it the same every time?", "So a design review compares layout, not a new paragraph. Change the count if you need more or less."],
    ["Can I use it in a live product?", "Only as placeholder. Replace it before you publish."],
  ),
  "remove-duplicate-lines": guide(
    "oak, ash, oak, pine becomes oak, ash, pine. The first copy of each line is kept, and later copies are dropped.",
    ["Is the comparison case-sensitive?", "Yes. Oak and oak are different lines."],
    ["Are blank lines removed?", "Only extra copies of a blank line. The first blank line stays."],
    ["Does the order change?", "No. Surviving lines stay in their original order."],
  ),
  "slug-generator": guide(
    "“Roof Pitch & Rafter Calculator” becomes roof-pitch-rafter-calculator. Accents are stripped, punctuation becomes a hyphen, and the result is lowercase.",
    ["What is a slug?", "The readable part of a URL. This site uses slugs such as roof-pitch-calculator."],
    ["Are ampersands kept?", "No. They’re treated as punctuation and replaced by a hyphen, then extra hyphens are collapsed."],
    ["Will two titles collide?", "They can. “Roof Pitch” and “Roof-pitch” become the same slug. Check the URL is free before you publish it."],
  ),
  "markdown-preview": guide(
    "A line starting with # is a heading. **quiet** is bold, a line starting with - is a list item, and [Nice Tools](https://nicetools.co) is a link.",
    ["Which Markdown is supported?", "Headings, paragraphs, bold, italic, inline code, unordered lists, and http(s) links. Tables, images, and raw HTML are not rendered."],
    ["Why is raw HTML shown as text?", "So a preview can’t run markup you pasted. The preview is a reader, not a browser."],
    ["Do line breaks inside a paragraph show?", "A blank line starts a new block. Single line breaks inside a paragraph are joined."],
  ),
  "markdown-table": guide(
    "Headers Name, Role, Note and two rows become a Markdown table with a header, a separator row of dashes, and one row per line.",
    ["How do I separate cells?", "Commas. Headers are one comma-separated line. Each data row is its own line, also comma-separated."],
    ["What if a cell contains a comma?", "Split the cell another way before you paste, or edit the Markdown after. This page splits on every comma."],
    ["Where can I use the result?", "In any Markdown file: GitHub, a docs site, or the Markdown Preview on this site."],
  ),
  "number-to-words": guide(
    "142 is “one hundred and forty two”. 1,001 is “one thousand one”. A negative number is prefixed with minus.",
    ["Which English is this?", "Australian and British style, with “and” after the hundreds: one hundred and twenty one."],
    ["Are decimals supported?", "Yes. 2.5 is “two point five”. Each digit after the point is spoken separately."],
    ["How large a number can I convert?", "Up to 999 billion. Beyond that, the page asks for a smaller number."],
  ),
  "text-cleaner": guide(
    "A line with extra spaces, a run of blank lines, and curly quotes becomes a single-spaced block with straight quotes and one blank line where there were several. Tick “Deduplicate lines” or “Sort lines” when a list needs it.",
    ["What does trim lines do?", "It removes spaces at the start and end of each line."],
    ["What does collapse spaces do?", "It turns two or more spaces or tabs in a line into one space."],
    ["What does straighten quotes do?", "Curly apostrophes and quotes become the plain ' and \" characters."],
    ["Are Windows line endings normalised?", "Yes. Carriage returns become ordinary line breaks before the other clean-ups run."],
  ),
}
