import { guide, type ToolGuideCopy } from "@/lib/tools/guides/types"

export const playGuides: Record<string, ToolGuideCopy> = {
  "dice-roller": guide(
    "Two dice showing 5 and 3 total 8. Tap one die to throw just that one again, or press Roll to throw them all. R does the same when you are not typing in a field.",
    ["How many dice can I roll?", "From 1 to 6. Use the plus and minus controls to change the count."],
    ["Are the rolls fair?", "Each face from 1 to 6 is equally likely. The roll uses the browser’s ordinary random number."],
    ["Is there a sound?", "No. The roll is visual only."],
  ),
  "age-calculator": guide(
    "A date of birth of 12 June 1994, with the as-of date set to 12 June 2026, is 32 years, 0 months, and 0 days.",
    ["How is the age counted?", "Whole years, then whole months, then the remaining days. If the day of the month has not arrived yet, the month count steps back."],
    ["What if the as-of date is before the birthday?", "There is no age to show. The later date has to be the as-of date."],
    ["Does this include the time of day?", "No. Both dates are treated as calendar days, not clock times."],
  ),
  "countdown": guide(
    "A date set for 9:00 two weeks from today starts near 14 days, and the hours, minutes, and seconds tick down from there.",
    ["What happens when the time passes?", "The heading changes to say that moment has passed, and the numbers count upward from then."],
    ["Which timezone is used?", "The date and time you pick are in your computer’s local timezone."],
    ["Does the page keep counting if I leave it open?", "Yes. It updates every second while the tab is open."],
  ),
  "name-picker": guide(
    "A list of Ava, Noah, Mia, Leo, and Sofia draws one name. With “remove after it is drawn” ticked, that name leaves the list so the next draw is from who is left.",
    ["Can the same name be drawn twice?", "Only if you untick remove. With it ticked, a drawn name is taken off the list."],
    ["How should I enter the names?", "One name a line. Blank lines are ignored."],
    ["Is the draw stored?", "No. Refreshing the page restores the starting list."],
  ),
  "coin-flip": guide(
    "Each press of Flip is a fresh heads or tails. Two flips in a row are independent, so heads does not make tails more likely next.",
    ["Is it a fair coin?", "Yes. The browser’s random source picks heads or tails with equal chance."],
    ["Can I flip more than once?", "Yes. Each press is a new flip. The page does not keep a history."],
    ["Can I weight the coin?", "No. It is always even odds."],
  ),
  "random-number": guide(
    "A minimum of 1 and a maximum of 100 draws a whole number in that range, including both ends. 1 and 100 can both appear.",
    ["Are the ends included?", "Yes. The draw is from the minimum through the maximum."],
    ["What if the minimum is higher than the maximum?", "The two ends are swapped, and the draw still lands between them."],
    ["Are decimals possible?", "No. The result is a whole number."],
  ),
  "random-choice": guide(
    "A list of Ada, Lin, Noor, and Sam, one name a line, picks one of those four. Blank lines are skipped.",
    ["Does a longer line get a better chance?", "No. Each non-blank line is one option, with an equal chance."],
    ["Can I pick without removing the choice?", "Yes. The list stays as you typed it. Use the Name Picker if you want a name removed after it is drawn."],
    ["What if two lines are the same?", "They are two separate entries, so that text is twice as likely."],
  ),
  "wheel-spinner": guide(
    "Four names, one a line, split the wheel into four equal slices. Spin rotates it, and the name at the top when it stops is the winner.",
    ["Are the slices equal?", "Yes. Each non-blank line gets the same angle."],
    ["How is the winner chosen?", "From the angle the wheel stops at, not from a separate random pick after the animation."],
    ["Can I use it for anything other than names?", "Yes. Any short label works: tasks, lunch spots, or the next person to talk."],
  ),
  "stopwatch": guide(
    "Start begins the clock. Lap records the time so far without stopping it. Stop freezes the clock, and Reset returns it to zero and clears the laps.",
    ["What does a lap store?", "The total elapsed time at the moment you press Lap, not the gap since the previous lap."],
    ["Does it keep running in the background?", "It keeps time while the tab is open. A browser may slow timers in a background tab."],
    ["How precise is it?", "The display updates about 20 times a second, from the browser’s performance clock."],
  ),
  "cooking-timer": guide(
    "10 minutes starts at 10:00 and counts down by the second. When it reaches zero it plays one short beep, if the browser allows sound.",
    ["Can I set seconds?", "The field is in minutes. 1.5 is ninety seconds."],
    ["Will it beep if the tab is in the background?", "It tries. Some browsers block sound until you have clicked the page."],
    ["Does Reset stop the beep?", "Reset clears the countdown. The beep is a single tone when the timer hits zero."],
  ),
  "recipe-scaler": guide(
    "A recipe for 4, scaled to 6, multiplies each leading quantity by 1.5. 2 cups of flour becomes 3, 1/2 tsp of salt becomes 0.75, and 1 1/2 tbsp of oil becomes 2.25.",
    ["Which numbers are scaled?", "A quantity at the start of a line. A number later in the sentence is left alone."],
    ["Are fractions understood?", "Yes. 1/2 and mixed numbers such as 1 1/2 are read, then written back as a decimal."],
    ["What if a line has no quantity?", "It is copied unchanged. “Salt to taste” stays as it is."],
  ),
  "world-clock": guide(
    "The page shows the current time in Sydney, Tokyo, London, New York, Los Angeles, and UTC, using your computer’s clock.",
    ["Can I add a city?", "Not on this page. The six zones are fixed."],
    ["Does daylight saving apply?", "Yes. Each zone uses the timezone database, so London and New York move with daylight saving and Sydney does too."],
    ["Why might it differ from my phone by a second?", "It updates once a second from the time your computer reports. A clock that is set wrong will be wrong here as well."],
  ),
  "gamepad-tester": guide(
    "Press a button on a connected controller and the page lists that controller, lights the button number that is down, and shows each stick axis from about −1 to 1.",
    ["Why does it say to press a button?", "Browsers only expose a controller after it has been used on the page."],
    ["Which controllers work?", "Any controller the browser reports as a standard gamepad, including most Xbox and PlayStation pads."],
    ["Do the button numbers match the labels on the pad?", "They match the browser’s button index, which follows the standard gamepad mapping. The index is what a game would read."],
  ),
  "keyboard-tester": guide(
    "Press A and that key lights up until you release it. The line under the keyboard names the last key that went down.",
    ["Does this block browser shortcuts?", "No. The page listens for keys without cancelling them, so a shortcut still does what the browser expects."],
    ["Which keys are drawn?", "The number row and the three letter rows. Other keys still update the “last key” line."],
    ["Can I test a keyboard that is not typing into a field?", "Yes. Focus the page, not a text box, and press the key."],
  ),
  "mouse-tester": guide(
    "Move inside the pad and the numbers follow the pointer. A click counts up and names the button: left, middle, or right.",
    ["Are the coordinates screen pixels?", "They are pixels inside the test pad, measured from its top-left corner."],
    ["Does a trackpad count?", "Yes. Any pointer that moves and clicks inside the pad is counted."],
    ["Why did a side button not register?", "The page reads the standard button index. Extra buttons on some mice are not reported by every browser."],
  ),
  "reaction-time": guide(
    "Click to start, wait for the panel to switch, then click again. A result of 240 ms means about a quarter of a second between the signal and your click.",
    ["What is a typical result?", "Many people land between 200 and 300 ms. Faster is not a medical measure, and one try is noisy."],
    ["What does “too soon” mean?", "You clicked before the signal. The wait is random, between about 0.8 and 3 seconds, so you cannot time it."],
    ["Does the first click count?", "The first click only starts the test. The time starts when the panel changes."],
  ),
  "cps-test": guide(
    "The test lasts five seconds. 30 clicks in that window is 6.0 clicks a second.",
    ["When does the clock start?", "On the first click. The next five seconds count every click, including that first one."],
    ["Is this the same as reaction time?", "No. Reaction time is one response to a signal. This is how many clicks you can make in five seconds."],
    ["Can I use a keyboard?", "The button is a click target. A mouse or trackpad click is what it counts."],
  ),
  "sensitivity-converter": guide(
    "800 DPI, a sensitivity of 1.2, and a yaw of 0.022 is about 43.30 cm for a full 360° turn.",
    ["What is yaw?", "The degrees the game turns for one count of mouse movement. 0.022 is common in Source-style games. Change it if your game uses another value."],
    ["What is cm/360?", "How far the mouse travels, in centimetres, to turn the view all the way around."],
    ["Does this change my game settings?", "No. It only converts the numbers you type."],
  ),
  "edpi-calculator": guide(
    "800 DPI times a sensitivity of 0.4 is an eDPI of 320.",
    ["What is eDPI?", "DPI multiplied by in-game sensitivity. It lets you compare settings when the DPI and the sensitivity differ."],
    ["Is eDPI the same across games?", "Only when those games treat sensitivity the same way. A different yaw means the same eDPI is a different turn."],
    ["Should I use this or cm/360?", "eDPI is the product of two settings. cm/360 is the distance on the mousepad. Use cm/360 when you are matching a feel between games."],
  ),
  "monitor-ppi-calculator": guide(
    "A 27 inch panel at 2560 × 1440 is about 108.8 pixels per inch.",
    ["How is PPI calculated?", "The pixel diagonal, from the width and height, divided by the physical diagonal in inches."],
    ["Does this use the size on the box?", "Use the panel’s actual diagonal, not the size of the stand or the outer frame."],
    ["How is this different from the screen PPI tool?", "This one uses the pixel counts you type. The screen PPI tool multiplies CSS pixels by this device’s pixel ratio."],
  ),
  "refresh-rate-tester": guide(
    "The number is how many animation frames the browser painted in the last half second, scaled up to a second. A 60 Hz panel usually sits near 60.",
    ["Is this the monitor’s rated refresh?", "It is the frame rate the browser is achieving on this page. A busy tab, or a battery saver, can sit below the panel’s rating."],
    ["Why does it move around?", "It is recounted every half second. Small swings of a frame or two are normal."],
    ["What is the moving bar for?", "It is a visual check that frames are arriving. The number is the measurement."],
  ),
  "dead-zone-tester": guide(
    "A dead zone of 0.15 treats any stick reading smaller than 0.15 as 0. A raw axis of 0.08 becomes an applied 0.00. A raw axis of 0.40 stays 0.40.",
    ["What is a dead zone?", "A band around the centre that is ignored, so a resting stick does not drift the camera."],
    ["Why do I need a controller?", "The readings come from a connected gamepad. Move a stick after pressing a button so the browser can see it."],
    ["Does this change the controller?", "No. It only shows what the raw value would become after that dead zone."],
  ),
  "screen-ppi-calculator": guide(
    "CSS pixels are multiplied by this screen’s device pixel ratio before the diagonal is applied. A ratio of 2 turns 1512 CSS pixels of width into 3,024 device pixels.",
    ["Why multiply by the device pixel ratio?", "CSS pixels are not always physical pixels. On a retina-style screen one CSS pixel is two or more device pixels."],
    ["What should I enter for the diagonal?", "The physical screen size in inches, the same number you would use for a monitor."],
    ["Will two laptops with the same CSS size match?", "Only if the pixel ratio and the physical diagonal match. The page reads the ratio from the browser you are using."],
  ),
  "battery-runtime-calculator": guide(
    "A 3,000 mAh battery with a steady 250 mA load runs for 12h 0m 0s, because 3,000 ÷ 250 is 12 hours.",
    ["Does this include the device switching itself off?", "No. It is capacity divided by a constant load. Real devices change their draw, and a battery is not used down to a true zero."],
    ["What units are these?", "Capacity is milliamp hours. Load is milliamps. The result is hours, minutes, and seconds."],
    ["Can I use watt hours?", "Only if you convert first. This page does not take voltage."],
  ),
  "crypto-profit-calculator": guide(
    "0.4 of a coin, bought at $90,000 and sold at $104,000, with a 0.1% fee on each side, costs $36,000 and returns $41,600 before fees. The fees are $77.60, so the profit is $5,522.40, about 15.34%.",
    ["Which fees are included?", "The percent you enter, applied once to the cost and once to the proceeds. A withdrawal or a network fee is extra unless you fold it into that percent."],
    ["Are these live prices?", "No. Nothing on this page reads a market. The prices are the ones you type."],
    ["Does this connect to a wallet?", "No. It is arithmetic in the browser."],
  ),
  "crypto-dca-calculator": guide(
    "$100 a buy, 12 buys, and an average price of $80 means $1,200 invested and 15 coins. At a current price of $110 those coins are worth $1,650, so the profit is $450.",
    ["What is the average price?", "The average you paid per coin, which you enter. The page does not reconstruct it from a list of fills."],
    ["Is the current price live?", "No. Type the price you want to test."],
    ["Does this include fees?", "No. Subtract fees from the profit if your buys were charged."],
  ),
  "crypto-staking-calculator": guide(
    "$1,000 at 5% APY for 365 days, without monthly compounding, earns $50. The balance is $1,050. Tick compound monthly and the earned amount rises a little, because each month’s interest starts earning too.",
    ["Is the rate a promise?", "No. It is the APY you type, applied for the number of days you type."],
    ["How does compounding work here?", "The APY is split into 12 monthly parts, then applied for the number of months in the period."],
    ["Does this stake anything?", "No. There is no wallet and no protocol. It only projects the numbers."],
  ),
  "crypto-position-size-calculator": guide(
    "A $10,000 account, risking 1%, can lose $100. An entry of $100 and a stop at $95 is $5 of risk per coin, so the size is 20 coins, a notional of $2,000.",
    ["What is the size?", "The risk amount divided by the distance from entry to stop. That is how many units you can hold before a stop-out costs the risk amount."],
    ["Does this place an order?", "No. It does not connect to an exchange."],
    ["What if the stop is above the entry?", "The distance is the absolute gap, so a short uses the same size maths."],
  ),
  "crypto-liquidation-calculator": guide(
    "A long entered at $100 with 10× leverage and 0.5% maintenance liquidates near $90.50. A short uses the same distance on the other side of the entry.",
    ["How is the price estimated?", "The move is 1 ÷ leverage, minus the maintenance percent. A long liquidates at entry times one minus that move."],
    ["Will an exchange match this number?", "Not exactly. Exchanges add fees and their own maintenance schedule. Treat this as a simplified isolated-margin estimate."],
    ["What if maintenance is too high for the leverage?", "The page says the leverage does not hold, because the maintenance already uses up the margin."],
  ),
  "crypto-gas-calculator": guide(
    "21,000 gas units at 20 gwei, with the coin at $4,000, is 0.00042 coin. That is $1.68.",
    ["What is a gwei?", "One billionth of the coin. The fee in coin is gas units × gwei × 0.000000001."],
    ["Is 21,000 the right gas limit?", "It is a common figure for a simple transfer. A contract call often uses more. Use the limit your wallet estimates."],
    ["Is the gas price live?", "No. Type the gwei and the coin price you want to test."],
  ),
  "crypto-apy-calculator": guide(
    "An 8% APR compounded 365 times a year is about an 8.33% APY. Switching the direction turns an APY back into the APR that would produce it.",
    ["What is the difference between APR and APY?", "APR is the rate before compounding. APY is what you earn over a year if that rate compounds as often as you set."],
    ["Which compounding matches a protocol?", "Use 365 for a daily compound and 12 for a monthly one. Some protocols compound every block, which this page does not model."],
    ["Is the rate from a live pool?", "No. You type the rate."],
  ),
  "crypto-converter": guide(
    "1.5 of a coin priced at $4,000 each is 6,000 in the currency you name. The labels are yours. The maths is amount times the price of one.",
    ["Does this use a market feed?", "No. The price of one is whatever you type, so the result is only as current as that number."],
    ["Can I convert the other way?", "Put the amount you have in the first field and the price of one unit in the rate field. To go from dollars back to coins, use a rate of one divided by the coin price."],
    ["Are the ticker labels checked?", "No. ETH and AUD are labels for the result line. They are not looked up."],
  ),
  "impermanent-loss-calculator": guide(
    "A pool position whose price doubles, a change of 100%, is worth about 5.72% less than simply holding the two assets. Fees you earned are not included, so they can offset that gap.",
    ["What is impermanent loss?", "The gap between providing liquidity and holding the same assets, after the price moves. It shrinks again if the price returns."],
    ["Does 100% mean the price doubled?", "Yes. The field is the percent change. 100 is a doubling. −50 is a halving."],
    ["Are trading fees included?", "No. The figure is only the value gap versus holding."],
  ),
  "bitcoin-halving-countdown": guide(
    "The countdown targets 20 April 2028, counted from the April 2024 halving and a block about every 10 minutes. The number of days shrinks as that date gets closer.",
    ["Is 20 April 2028 the real halving?", "It is an estimate. Blocks are not exactly 10 minutes, so the network moves the date."],
    ["What is a halving?", "The reward paid to miners is cut in half. It is a schedule in the protocol, not a price event this page predicts."],
    ["Does this page trade or hold bitcoin?", "No. It is a date countdown only."],
  ),
}
