import type { Category, ToolEntry, ToolStatus } from "@/lib/registry"

function tool(
  category: Category,
  slug: string,
  title: string,
  description: string,
  status: ToolStatus = "live",
  extra?: Pick<ToolEntry, "featured" | "tags" | "cluster" | "seoTitle" | "related">,
): ToolEntry {
  return { slug, category, title, description, route: `/${category}/${slug}`, status, ...extra }
}

const soon = "coming-soon" as const

export const libraryTools: ToolEntry[] = [
  tool("calculators", "general-calculator", "General Calculator", "Add, subtract, multiply, and divide — with brackets — right here in the browser.", "live", { cluster: "numbers", tags: ["maths", "arithmetic"] }),
  tool("calculators", "loan-calculator", "Loan Calculator", "See the monthly repayment, the interest, and the total you'll pay on a fixed loan.", "live", { cluster: "debt", tags: ["loan", "repayment", "interest"] }),
  tool("calculators", "compound-interest-calculator", "Compound Interest Calculator", "Watch a balance grow when interest and regular deposits keep stacking.", "live", { cluster: "growth", tags: ["interest", "compound", "savings"] }),
  tool("calculators", "savings-calculator", "Savings Calculator", "Project where your savings land from a starting amount and a monthly deposit.", "live", { cluster: "growth", tags: ["savings", "deposit"] }),
  tool("calculators", "roi-calculator", "ROI Calculator", "Turn what you put in and what you got back into profit and ROI.", "live", { cluster: "growth", tags: ["roi", "profit", "return"] }),
  tool("calculators", "sales-tax-calculator", "Sales Tax Calculator", "Add tax to a price, or pull the tax back out of a total you've already been quoted.", "live", { cluster: "percentage", tags: ["gst", "tax", "vat"] }),
  tool("calculators", "time-duration-calculator", "Time Duration Calculator", "Find the time between two clocks — including when the span runs overnight.", "live", { cluster: "numbers", tags: ["time", "duration"] }),
  tool("calculators", "date-difference-calculator", "Date Difference Calculator", "Count the days, weeks, and months between two dates.", "live", { cluster: "numbers", tags: ["date", "days"] }),
  tool("calculators", "take-home-salary-calculator", "Take-home Salary Calculator", "Estimate Australian resident tax, the Medicare levy, and what you'd take home.", "live", { cluster: "pay", tags: ["salary", "tax", "ato"] }),
  tool("calculators", "salary-to-hourly-calculator", "Salary to Hourly Calculator", "Turn an annual salary into an hourly rate from the hours and weeks you work.", "live", { cluster: "pay", tags: ["salary", "hourly"] }),
  tool("calculators", "overtime-calculator", "Overtime Calculator", "Price ordinary hours and overtime from an hourly rate and a multiplier.", "live", { cluster: "pay", tags: ["overtime", "pay"] }),
  tool("calculators", "bmi-calculator", "BMI Calculator", "Work out body mass index from height and weight, then see the adult screening band.", "live", { cluster: "body", tags: ["bmi", "health"] }),
  tool("calculators", "calorie-calculator", "Calorie Calculator", "Get a daily calorie guide from your details and whether you want to lose, maintain, or gain.", "live", { cluster: "body", tags: ["calories", "tdee"] }),
  tool("calculators", "bmr-calculator", "BMR Calculator", "Estimate basal metabolic rate with the Mifflin–St Jeor equation.", "live", { cluster: "body", tags: ["bmr", "metabolism"] }),
  tool("calculators", "tdee-calculator", "TDEE Calculator", "Estimate daily energy use from your BMR and how active the day is.", "live", { cluster: "body", tags: ["tdee", "calories"] }),
  tool("calculators", "gpa-calculator", "GPA Calculator", "Work out a credit-weighted GPA on a 4.0 scale.", "live", { cluster: "school", tags: ["gpa", "grades"] }),
  tool("calculators", "grade-calculator", "Grade Calculator", "Turn points earned into a percentage and a letter grade.", "live", { cluster: "school", tags: ["grade", "percent"] }),
  tool("calculators", "unit-converter", "Unit Converter", "Convert length, weight, temperature, volume, and area — pick the pair and type the number.", "live", { cluster: "numbers", tags: ["units", "convert"] }),

  tool("developer", "password-generator", "Password Generator", "Make a random password in this browser. Nothing is stored or sent.", "live", { cluster: "ids", tags: ["password", "generator", "random"] }),
  tool("developer", "base64-encoder", "Base64 Encoder / Decoder", "Encode text as Base64, or decode it back — useful for data URLs and text channels.", "live", { cluster: "encode", tags: ["base64", "encode", "decode"] }),
  tool("developer", "url-encoder", "URL Encoder / Decoder", "Encode or decode text so it sits safely in a query string.", "live", { cluster: "encode", tags: ["url", "encode", "percent"] }),
  tool("developer", "timestamp-converter", "Timestamp Converter", "Switch between a Unix timestamp and a readable date.", "live", { tags: ["unix", "timestamp", "epoch"] }),
  tool("developer", "hash-generator", "Hash Generator", "SHA hashes of text, calculated in this browser.", "live", { cluster: "encode", tags: ["hash", "sha-256", "sha"] }),
  tool("developer", "jwt-decoder", "JWT Decoder", "Read a JWT header and payload. The signature isn't checked — this is a decoder, not a verifier.", "live", { cluster: "encode", tags: ["jwt", "token", "decode"] }),
  tool("developer", "json-validator", "JSON Validator", "Check that a JSON document parses, and see the line if it doesn't.", "live", { cluster: "json", tags: ["json", "validate"] }),
  tool("developer", "sql-formatter", "SQL Formatter", "Break a SQL statement onto readable lines so you can actually scan it.", "live", { cluster: "format", tags: ["sql", "format"] }),
  tool("developer", "xml-formatter", "XML Formatter", "Indent an XML document so the structure is easier to see.", "live", { cluster: "format", tags: ["xml", "format"] }),
  tool("developer", "cron-expression-generator", "Cron Expression Generator", "Build a five-field cron expression and a plain-language reading of when it runs.", "live", { cluster: "ops", tags: ["cron", "schedule"] }),
  tool("developer", "html-encoder", "HTML Encoder / Decoder", "Escape HTML characters, or turn the escapes back into text.", "live", { cluster: "encode", tags: ["html", "escape", "encode"] }),
  tool("developer", "code-beautifier", "Code Beautifier", "Pretty-print JSON, or indent a brace-style snippet.", "live", { cluster: "json", tags: ["json", "format", "indent"] }),
  tool("developer", "json-to-csv", "JSON to CSV Converter", "Turn a JSON array of objects into a CSV table you can copy.", "live", { cluster: "json", tags: ["json", "csv", "convert"] }),
  tool("developer", "json-schema-generator", "JSON Schema Generator", "Infer a readable JSON Schema from a JSON document you paste.", "live", { cluster: "json", tags: ["json", "schema"] }),
  tool("developer", "password-strength-checker", "Password Strength Checker", "Estimate password strength in this browser. Nothing is sent anywhere.", "live", { cluster: "ids", tags: ["password", "strength"] }),
  tool("developer", "email-header-analyzer", "Email Header Analyzer", "Parse raw email headers into sender, routing, dates, and SPF/DKIM/DMARC tokens.", "live", { cluster: "ops", tags: ["email", "headers", "spf"] }),
  tool("developer", "ai-context-window-calculator", "AI Context Window Calculator", "Estimate how much of a model’s context window a prompt and reply would use.", "live", { cluster: "ai-dev", tags: ["tokens", "context", "ai"] }),
  tool("developer", "prompt-cost-calculator", "Prompt Cost Calculator", "Estimate per-request, daily, and monthly token cost from published prices you can check.", "live", { cluster: "ai-dev", tags: ["tokens", "cost", "ai"] }),
  tool("developer", "csv-to-json", "CSV to JSON Converter", "Turn a CSV table into a JSON array of objects.", "live", { cluster: "json", tags: ["csv", "json", "convert"] }),
  tool("developer", "yaml-validator", "YAML Validator", "Check a YAML document and show the first problem we find.", "live", { cluster: "yaml", tags: ["yaml", "validate"] }),
  tool("developer", "yaml-to-json", "YAML to JSON Converter", "Convert straightforward YAML into JSON.", "live", { cluster: "yaml", tags: ["yaml", "json", "convert"] }),
  tool("developer", "robots-txt-generator", "Robots.txt Generator", "Write a robots.txt from the paths you allow and block.", "live", { cluster: "ops", tags: ["robots", "seo"] }),
  tool("developer", "domain-age-checker", "Domain Age Checker", "Look up when a domain was registered.", soon),
  tool("developer", "chmod-calculator", "Chmod Calculator", "Tick permissions and get the octal mode and the symbol form.", "live", { cluster: "ops", tags: ["chmod", "unix"] }),
  tool("developer", "subnet-calculator", "Subnet Calculator", "See the network, broadcast, and usable hosts for an IPv4 prefix.", "live", { cluster: "network", tags: ["subnet", "ipv4", "cidr"] }),
  tool("developer", "cidr-calculator", "CIDR Calculator", "Read an address/prefix and show the network it belongs to.", "live", { cluster: "network", tags: ["cidr", "ipv4", "subnet"] }),
  tool("developer", "jsonpath-tester", "JSONPath Tester", "Try a JSONPath against a JSON document and see what matches.", "live", { cluster: "json", tags: ["json", "jsonpath"] }),
  tool("developer", "csp-header-generator", "CSP Header Generator", "Assemble a Content-Security-Policy header from the sources you allow.", "live", { cluster: "ops", tags: ["csp", "security", "header"] }),
  tool("developer", "utm-link-builder", "UTM Link Builder", "Add campaign parameters to a URL so you can tell where a visit came from.", "live", { cluster: "ops", tags: ["utm", "url", "campaign"] }),

  tool("files-media", "pdf-splitter", "PDF Splitter", "Split one PDF into separate files.", soon),
  tool("files-media", "pdf-compressor", "PDF Compressor", "Reduce the size of a PDF.", soon),
  tool("files-media", "pdf-to-word", "PDF to Word", "Convert a PDF into an editable document.", soon),
  tool("files-media", "word-to-pdf", "Word to PDF", "Convert a Word document into a PDF.", soon),
  tool("files-media", "pdf-to-jpg", "PDF to JPG", "Export PDF pages as JPEG images.", soon),
  tool("files-media", "jpg-to-pdf", "JPG to PDF", "Place JPEG images into a PDF.", soon),
  tool("files-media", "image-resizer", "Image Resizer", "Resize an image in the browser and download the result. Your files stay on your device.", "live", { seoTitle: "Image Resizer", tags: ["resize image", "image resizer", "resize jpg", "resize png"], related: ["image-compressor", "image-cropper", "png-to-jpg", "svg-to-png"] }),
  tool("files-media", "image-cropper", "Image Cropper", "Crop an image in the browser and download the result. Your files stay on your device.", "live", { seoTitle: "Image Cropper", tags: ["crop image", "crop jpg", "crop png"], related: ["image-resizer", "screenshot-annotator", "exif-stripper"] }),
  tool("files-media", "jpg-to-png", "JPG to PNG", "Convert a JPEG to PNG in your browser. Your files stay on your device.", "live", { seoTitle: "JPG to PNG Converter", tags: ["jpg to png", "jpeg to png", "convert jpg"], related: ["png-to-jpg", "webp-to-jpg", "image-compressor"] }),
  tool("files-media", "png-to-jpg", "PNG to JPG", "Convert a PNG to JPEG in your browser — transparency becomes white.", "live", { seoTitle: "PNG to JPG Converter", tags: ["png to jpg", "png to jpeg", "convert png"], related: ["jpg-to-png", "image-compressor", "webp-to-jpg"] }),
  tool("files-media", "webp-to-jpg", "WebP to JPG", "Convert a WebP image to JPEG in the browser. Your files stay on your device.", "live", { seoTitle: "WebP to JPG Converter", tags: ["webp to jpg", "webp to jpeg", "convert webp"], related: ["png-to-jpg", "jpg-to-png", "image-compressor"] }),
  tool("files-media", "heic-to-jpg", "HEIC to JPG", "Convert an HEIC photo to JPEG.", soon),
  tool("files-media", "svg-to-png", "SVG to PNG", "Rasterise an SVG to PNG in the browser. Your files stay on your device.", "live", { seoTitle: "SVG to PNG Converter", tags: ["svg to png", "convert svg", "rasterise svg"], related: ["image-resizer", "image-to-base64", "jpg-to-png"] }),
  tool("files-media", "image-to-base64", "Image to Base64", "Turn an image into a Base64 data URL you can paste into CSS or HTML.", "live", { seoTitle: "Image to Base64", tags: ["image to base64", "data url", "base64 image"], related: ["svg-to-png", "jpg-to-png", "image-compressor"] }),
  tool("files-media", "pdf-signer", "PDF Signer", "Place a signature on a PDF page in this browser and download a signed copy.", "live", { seoTitle: "Sign PDF", tags: ["sign pdf", "pdf signature", "sign document"], related: ["pdf-merger", "pdf-to-text", "pdf-ocr"] }),
  tool("files-media", "pdf-ocr", "PDF OCR / Text Extractor", "Extract selectable text, or run OCR on a scanned PDF. The file stays on your device.", "live", { seoTitle: "PDF OCR", tags: ["pdf ocr", "extract text from pdf", "scanned pdf"], related: ["pdf-to-text", "pdf-signer", "pdf-merger"] }),
  tool("files-media", "pdf-to-text", "PDF to Text", "Pull the selectable text out of a PDF and copy or download it.", "live", { seoTitle: "Extract Text from PDF", tags: ["extract text from pdf", "pdf to text", "pdf text"], related: ["pdf-ocr", "pdf-merger", "pdf-signer"] }),
  tool("files-media", "gif-maker", "GIF Maker", "Turn images or a short video into a GIF, with frame order and timing you control.", "live", { seoTitle: "GIF Maker", tags: ["gif maker", "make gif", "video to gif"], related: ["video-trimmer", "screenshot-annotator", "image-resizer"] }),
  tool("files-media", "video-trimmer", "Video Trimmer", "Clip a video between two points and download the selection.", "live", { seoTitle: "Video Trimmer", tags: ["trim video", "cut video", "video clip"], related: ["audio-trimmer", "gif-maker"] }),
  tool("files-media", "audio-trimmer", "Audio Trimmer", "Clip an audio file between two points and download a WAV.", "live", { seoTitle: "Audio Trimmer", tags: ["trim audio", "cut mp3", "audio clip"], related: ["video-trimmer", "gif-maker"] }),
  tool("files-media", "screenshot-annotator", "Screenshot Annotator", "Crop, arrow, box, blur, and label a screenshot, then download the image.", "live", { seoTitle: "Screenshot Annotator", tags: ["annotate screenshot", "screenshot arrow", "blur screenshot"], related: ["screenshot-beautifier", "image-cropper", "exif-stripper"] }),
  tool("files-media", "screenshot-beautifier", "Screenshot Beautifier", "Frame a screenshot with padding, radius, shadow, and optional window chrome.", "live", { seoTitle: "Screenshot Beautifier", tags: ["screenshot frame", "browser mockup", "screenshot padding"], related: ["screenshot-annotator", "image-resizer"] }),
  tool("files-media", "background-remover", "Background Remover", "Remove the background from a photo.", soon),
  tool("files-media", "video-compressor", "Video Compressor", "Reduce the size of a video.", soon),
  tool("files-media", "mp4-to-mp3", "MP4 to MP3", "Pull the audio track out of a video.", soon),
  tool("files-media", "video-to-gif", "Video to GIF", "Turn a short video into a GIF.", soon),
  tool("files-media", "audio-converter", "Audio Converter", "Convert between audio formats.", soon),

  tool("design-creative", "colour-picker", "Colour Picker", "Pick a colour and copy the hex, RGB, and HSL.", "live", { cluster: "colour", seoTitle: "Colour Picker", tags: ["colour", "hex", "rgb", "hsl", "picker"] }),
  tool("design-creative", "hex-to-rgb", "HEX to RGB Converter", "Turn a hex colour into red, green, and blue — plus HSL.", "live", { cluster: "colour", seoTitle: "HEX to RGB Converter", tags: ["hex", "rgb", "colour", "convert"] }),
  tool("design-creative", "rgb-to-hex", "RGB to HEX Converter", "Turn red, green, and blue into hex.", "live", { cluster: "colour", seoTitle: "RGB to HEX Converter", tags: ["rgb", "hex", "colour", "convert"] }),
  tool("design-creative", "favicon-generator", "Favicon Generator", "Draw a letter favicon and download a PNG.", "live", { cluster: "identity", seoTitle: "Favicon Generator", tags: ["favicon", "icon", "png"] }),
  tool("design-creative", "aspect-ratio-calculator", "Aspect Ratio Calculator", "Find the missing side, or simplify a ratio you already have.", "live", { cluster: "css", seoTitle: "Aspect Ratio Calculator", tags: ["aspect ratio", "16:9", "layout"] }),
  tool("design-creative", "px-to-rem", "PX to REM Converter", "Convert pixels to rem from the root font size you use.", "live", { cluster: "css", seoTitle: "PX to REM Converter", tags: ["px", "rem", "css", "typography"] }),
  tool("design-creative", "font-identifier", "Font Identifier", "Identify a font from a sample.", soon),
  tool("design-creative", "box-shadow-generator", "Box Shadow Generator", "Dial in a CSS box-shadow and copy it.", "live", { cluster: "css", seoTitle: "Box Shadow Generator", tags: ["box-shadow", "css", "shadow"] }),
  tool("design-creative", "border-radius-generator", "Border Radius Generator", "Set a corner radius and copy the CSS.", "live", { cluster: "css", seoTitle: "Border Radius Generator", tags: ["border-radius", "css", "corners"] }),
  tool("design-creative", "css-grid-generator", "CSS Grid Generator", "Dial in columns, rows, and gaps, then copy clean CSS with a live preview.", "live", { cluster: "css", seoTitle: "CSS Grid Generator", tags: ["css grid", "layout", "css"] }),
  tool("design-creative", "open-graph-image-generator", "Open Graph Image Generator", "Make a 1200 × 630 social sharing image from a title, subtitle, and optional logo.", "live", { cluster: "identity", seoTitle: "Open Graph Image Generator", tags: ["open graph", "og image", "social"] }),

  tool("data-viz", "flowchart-generator", "Flowchart Generator", "Build a process flow with steps, decisions, and branches — no graph syntax."),
  tool("data-viz", "bar-chart-generator", "Bar Chart Generator", "Paste labels and values, get a bar chart you can customise and export."),
  tool("data-viz", "line-chart-generator", "Line Chart Generator", "Plot one or more series over time, with a sensible scale and a clean export."),
  tool("data-viz", "pie-chart-generator", "Pie Chart Generator", "Turn a short list of parts into a pie or donut, with labels and a legend."),
  tool("data-viz", "timeline-generator", "Timeline Generator", "Lay events on a timeline from ordinary dates — years, quarters, months, or days."),
  tool("data-viz", "diagram-generator", "Diagram Generator", "Place named boxes, connect them, and export a simple diagram."),
  tool("data-viz", "scatter-plot", "Scatter Plot Generator", "Plot X against Y, with series, labels, and an export you can drop into a slide."),
  tool("data-viz", "waterfall-chart", "Waterfall Chart Generator", "Show how a total is built from positive and negative changes, with connector lines."),

  tool("business", "resume-builder", "Resume Builder", "Fill in a one-page resume and print it — or save it as a PDF."),
  tool("business", "cover-letter-generator", "Cover Letter Generator", "Shape a cover letter from the points you want to make. No AI, just your words."),
  tool("business", "receipt-generator", "Receipt Generator", "Create a simple GST receipt with line items, then print or copy it.", "live", { cluster: "billing", seoTitle: "Receipt Generator", tags: ["receipt", "gst", "print"] }),
  tool("business", "link-shortener", "Link Shortener", "Create a short link that redirects.", soon),
  tool("business", "qr-code-generator", "QR Code Generator", "Make a QR code from text or a URL and download it."),
  tool("business", "break-even-calculator", "Break-even Calculator", "Find how many sales cover your fixed costs from price and variable cost.", "live", { cluster: "billing", seoTitle: "Break-even Calculator", tags: ["break-even", "contribution", "sales"] }),
  tool("business", "commission-calculator", "Commission Calculator", "Calculate commission from a sale amount and a rate.", "live", { cluster: "billing", seoTitle: "Commission Calculator", tags: ["commission", "sales", "rate"] }),
  tool("business", "youtube-rpm-calculator", "YouTube RPM Calculator", "Estimate earnings from views and the RPM you enter."),
  tool("business", "tiktok-earnings-calculator", "TikTok Earnings Calculator", "Estimate earnings from views and the RPM you enter."),
  tool("business", "creator-rate-calculator", "Creator Rate Calculator", "A starting rate from audience size and engagement — a conversation starter, not a quote."),
  tool("business", "paypal-fee-calculator", "PayPal Fee Calculator", "Fee and net amount from a PayPal-style rate you can edit."),
  tool("business", "stripe-fee-calculator", "Stripe Fee Calculator", "Fee and net amount from a Stripe-style rate you can edit."),
  tool("business", "etsy-fee-calculator", "Etsy Fee & Profit Calculator", "Listing, transaction, and payment fees against what the item cost."),
  tool("business", "ebay-fee-calculator", "eBay Fee & Profit Calculator", "Final value and payment fees against what the item cost."),
  tool("business", "amazon-fba-calculator", "Amazon FBA Profit Calculator", "Referral and fulfilment fees against what the item cost."),
  tool("business", "shopify-margin-calculator", "Shopify Profit Margin Calculator", "Payment fees and product cost on a Shopify order."),
  tool("business", "upwork-fee-calculator", "Upwork Fee Calculator", "What remains after an Upwork-style service fee you can edit."),
  tool("business", "fiverr-fee-calculator", "Fiverr Fee Calculator", "What remains after a Fiverr-style service fee you can edit."),
  tool("business", "gumroad-fee-calculator", "Gumroad Fee Calculator", "What remains after a Gumroad-style fee you can edit."),
  tool("business", "kickstarter-fee-calculator", "Kickstarter Fee Calculator", "Platform and payment fees on a pledge you type."),

  tool("home-trade", "concrete-calculator", "Concrete Calculator", "How much concrete a slab or footing needs — cubic metres, 20 kg bags, and a truck round-up.", "live", { seoTitle: "Concrete Calculator", tags: ["concrete", "slab", "volume", "bags", "m3"], related: ["gravel-calculator", "material-estimator", "paver-calculator", "construction-estimate-generator"] }),
  tool("home-trade", "gravel-calculator", "Gravel Calculator", "How much gravel you need from the area and depth — cubic metres and tonnes.", "live", { seoTitle: "Gravel Calculator", tags: ["gravel", "volume", "tonnes", "path"], related: ["concrete-calculator", "mulch-calculator", "paver-calculator", "material-estimator"] }),
  tool("home-trade", "mulch-calculator", "Mulch Calculator", "How much mulch a garden bed needs — cubic metres, litres, and 25 L bags.", "live", { seoTitle: "Mulch Calculator", tags: ["mulch", "garden", "volume", "litres"], related: ["gravel-calculator", "concrete-calculator", "paver-calculator"] }),
  tool("home-trade", "roof-pitch-calculator", "Roof Pitch & Rafter Calculator", "Pitch angle and rafter length from the rise and run you measure.", "live", { seoTitle: "Roof Pitch Calculator", tags: ["roof pitch", "rafter", "rise", "run"], related: ["roofing-calculator", "roofing-shingle-calculator", "gutter-calculator"] }),
  tool("home-trade", "tile-calculator", "Tile Calculator", "How many tiles a floor needs, including waste — square or rectangular.", "live", { seoTitle: "Tile Calculator", tags: ["tile", "floor", "waste", "how many tiles"], related: ["paver-calculator", "paint-calculator", "material-estimator", "drywall-calculator"] }),
  tool("home-trade", "drywall-calculator", "Drywall Calculator", "How many 2400 × 1200 mm plasterboard sheets a wall needs, with waste.", "live", { seoTitle: "Drywall Calculator", tags: ["drywall", "plasterboard", "sheets"], related: ["material-estimator", "stud-wall-calculator", "paint-calculator", "tile-calculator"] }),
  tool("home-trade", "fence-calculator", "Fence Calculator", "Posts and rails for a run of fence, counting both ends.", "live", { seoTitle: "Fence Calculator", tags: ["fence", "posts", "rails"], related: ["deck-calculator", "stud-wall-calculator", "material-estimator", "gutter-calculator"] }),
  tool("home-trade", "deck-calculator", "Deck Calculator", "How many deck boards you need from the area, the board width, and a waste allowance.", "live", { seoTitle: "Deck Calculator", tags: ["deck", "decking", "boards"], related: ["fence-calculator", "paver-calculator", "board-foot-calculator", "material-estimator"] }),
  tool("home-trade", "paver-calculator", "Paver Calculator", "How many pavers cover an area, with waste you can change.", "live", { seoTitle: "Paver Calculator", tags: ["paver", "paving", "waste"], related: ["tile-calculator", "concrete-calculator", "gravel-calculator", "deck-calculator"] }),
  tool("home-trade", "roofing-calculator", "Roofing Calculator", "Sloped roof area from the plan area and the pitch, plus waste to order.", "live", { seoTitle: "Roofing Calculator", tags: ["roof area", "pitch", "roofing"], related: ["roof-pitch-calculator", "roofing-shingle-calculator", "gutter-calculator"] }),
  tool("home-trade", "roofing-shingle-calculator", "Roofing Shingle Calculator", "Bundles of shingles from the roof area and the cover per bundle, plus waste.", "live", { seoTitle: "Roofing Shingle Calculator", tags: ["shingles", "roofing", "bundles"], related: ["roofing-calculator", "roof-pitch-calculator", "gutter-calculator"] }),
  tool("home-trade", "gutter-calculator", "Gutter Calculator", "Gutter length and a rough downpipe count — a spacing guide, not a drainage design.", "live", { seoTitle: "Gutter Calculator", tags: ["gutter", "downpipe", "roof"], related: ["roofing-calculator", "roof-pitch-calculator", "fence-calculator"] }),
  tool("home-trade", "hvac-btu-calculator", "HVAC BTU Calculator", "A rough cooling load from the floor area — a range in kW, not a specification.", "live", { seoTitle: "HVAC BTU Calculator", tags: ["hvac", "btu", "air conditioning", "kw"], related: ["paint-calculator", "material-estimator"] }),
  tool("home-trade", "board-foot-calculator", "Board Foot Calculator", "Board feet from thickness, width, and length — millimetres in, board feet out.", "live", { seoTitle: "Board Foot Calculator", tags: ["board feet", "timber", "lumber"], related: ["stud-wall-calculator", "deck-calculator", "material-estimator"] }),
  tool("home-trade", "stair-stringer-calculator", "Stair Stringer Calculator", "Risers, goings, and stringer length for a total rise — geometry, not a code certificate.", "live", { seoTitle: "Stair Stringer Calculator", tags: ["stair", "stringer", "riser", "going"], related: ["stud-wall-calculator", "deck-calculator", "board-foot-calculator"] }),
  tool("home-trade", "stud-wall-calculator", "Stud Wall Calculator", "How many studs a wall needs at the spacing you set, counting both ends.", "live", { seoTitle: "Stud Wall Calculator", tags: ["studs", "wall", "framing", "450mm"], related: ["material-estimator", "drywall-calculator", "board-foot-calculator", "fence-calculator"] }),
  tool("home-trade", "construction-estimate-generator", "Construction Estimate Generator", "Add up line costs and apply a markup on top — a working total, not a formal quote.", "live", { seoTitle: "Construction Estimate Generator", tags: ["estimate", "markup", "quote", "costs"], related: ["material-estimator", "quote-builder", "invoice-generator", "concrete-calculator"] }),

  tool("people-teams", "team-working-agreement", "Team Working Agreement Generator", "Draft a short working agreement from a few decisions you already made."),
  tool("people-teams", "meeting-agenda", "Meeting Agenda Generator", "Turn a list of items into a one-page agenda you can copy."),
  tool("people-teams", "one-on-one-agenda", "1:1 Agenda Generator", "A simple agenda for a one-to-one — what changed, what's stuck, what's next."),
  tool("people-teams", "team-icebreaker", "Team Icebreaker Generator", "Draw a light prompt for the start of a meeting."),

  tool("text-tools", "character-counter", "Character Counter", "Count characters, with and without spaces, plus the lines."),
  tool("text-tools", "readability-checker", "Readability Score Checker", "A Flesch reading-ease score for a piece of text you paste."),
  tool("text-tools", "reading-time", "Reading Time Calculator", "How long a text takes to read at the pace you set."),
  tool("text-tools", "lorem-ipsum", "Lorem Ipsum Generator", "Placeholder paragraphs for a layout — the same text each time, so the page doesn't jump."),
  tool("text-tools", "remove-duplicate-lines", "Remove Duplicate Lines", "Keep the first copy of each line and drop the rest."),
  tool("text-tools", "slug-generator", "Slug Generator", "A URL slug from a title — lowercase, hyphenated, ready to paste."),
  tool("text-tools", "markdown-preview", "Markdown Preview", "Preview headings, lists, links, and emphasis as you type."),
  tool("text-tools", "markdown-table", "Markdown Table Generator", "Build a Markdown table from headers and rows."),
  tool("text-tools", "number-to-words", "Number to Words Converter", "Write a number out in words."),
  tool("text-tools", "text-cleaner", "Text Cleaner", "Trim lines, collapse spaces, and tidy a block of text."),

  tool("everyday-fun", "coin-flip", "Coin Flip", "Flip a coin — even odds, a fresh flip every time."),
  tool("everyday-fun", "random-number", "Random Number Generator", "Draw a whole number between two bounds, including both ends."),
  tool("everyday-fun", "random-choice", "Random Choice Picker", "Pick one line from a list, at random."),
  tool("everyday-fun", "wheel-spinner", "Wheel Spinner", "Spin a wheel of names or options and see who lands at the top."),
  tool("everyday-fun", "stopwatch", "Stopwatch", "Start, stop, and lap a stopwatch."),
  tool("everyday-fun", "cooking-timer", "Cooking Timer", "Count down a kitchen timer — minutes, and a beep if the browser allows it."),
  tool("everyday-fun", "recipe-scaler", "Recipe Scaler", "Scale ingredient quantities to a new number of serves."),
  tool("everyday-fun", "world-clock", "World Clock", "The time in a handful of cities, including daylight saving."),
  tool("everyday-fun", "time-zone-meeting-planner", "Time Zone Meeting Planner", "Line up a few cities, see local times, and find hours that sit inside a working day."),

  tool("gaming-hardware", "gamepad-tester", "Online Gamepad Tester", "See buttons and sticks from a connected controller."),
  tool("gaming-hardware", "keyboard-tester", "Keyboard Tester", "See which keys are down — and the last key you pressed."),
  tool("gaming-hardware", "mouse-tester", "Mouse Tester", "Track position, buttons, and clicks inside the pad."),
  tool("gaming-hardware", "reaction-time", "Reaction Time Test", "How quickly you click when the screen changes."),
  tool("gaming-hardware", "cps-test", "CPS Test", "Clicks per second over a short burst."),
  tool("gaming-hardware", "sensitivity-converter", "Gaming Sensitivity / eDPI Calculator", "Compare DPI, sensitivity, and eDPI, and convert between games that share a known yaw."),
  tool("gaming-hardware", "edpi-calculator", "eDPI Calculator", "Effective DPI from DPI and in-game sensitivity, plus conversions for games with a documented yaw."),
  tool("gaming-hardware", "fov-calculator", "FOV Calculator", "Convert horizontal and vertical field of view at a given aspect ratio, with a few game presets."),
  tool("gaming-hardware", "monitor-ppi-calculator", "Monitor PPI Calculator", "Pixels per inch from a resolution and a screen size."),
  tool("gaming-hardware", "refresh-rate-tester", "Refresh Rate Tester", "Measure the frame rate this display is delivering right now."),
  tool("gaming-hardware", "dead-zone-tester", "Controller Dead-Zone Tester", "See stick drift and try a dead-zone."),
  tool("gaming-hardware", "screen-ppi-calculator", "Screen PPI Calculator", "PPI for this screen, using its device pixel ratio."),
  tool("gaming-hardware", "battery-runtime-calculator", "Battery Runtime Calculator", "How long a battery lasts at a load you type."),

  tool("crypto", "crypto-momentum-scanner", "Crypto Momentum Scanner", "Spot crypto volume breakouts and rising momentum across timeframes, free.", "live", {
    featured: true,
    seoTitle: "Crypto Momentum Scanner: Free Crypto Screener for Breakouts",
    tags: ["crypto screener", "crypto scanner", "crypto momentum scanner", "crypto breakout scanner", "crypto movers"],
  }),
  tool("crypto", "crypto-profit-calculator", "Crypto Profit Calculator", "Work out exactly what you walked away with — enter your entry price, exit price, and fees, and we'll handle the rest."),
  tool("crypto", "crypto-dca-calculator", "Crypto DCA Calculator", "See what a regular buy is worth against a current price you type."),
  tool("crypto", "crypto-staking-calculator", "Crypto Staking Calculator", "Simple or monthly-compounded staking yield from the rate you enter."),
  tool("crypto", "crypto-position-size-calculator", "Crypto Position Size Calculator", "Position size from account risk and a stop — no exchange, no order."),
  tool("crypto", "crypto-liquidation-calculator", "Crypto Liquidation Calculator", "A rough liquidation price from leverage and maintenance margin."),
  tool("crypto", "crypto-gas-calculator", "Crypto Gas Fee Calculator", "Gas units and gwei, priced in the coin you name."),
  tool("crypto", "crypto-apy-calculator", "Crypto APY / APR Calculator", "Convert between APR and APY from the rate you type."),
  tool("crypto", "crypto-converter", "Crypto Converter", "Convert an amount with a rate you supply. No live market feed."),
  tool("crypto", "impermanent-loss-calculator", "Impermanent Loss Calculator", "How a price change diverges from simply holding — fees not included."),
  tool("crypto", "bitcoin-halving-countdown", "Bitcoin Halving Countdown", "A countdown to the estimated next Bitcoin halving."),
  tool("crypto", "crypto-tax-calculator", "Crypto Tax Gain/Loss Calculator", "FIFO realised gains and losses from the buys and sells you enter. An estimate, not a lodgement."),
  tool("crypto", "crypto-dca-backtest-calculator", "Crypto DCA Backtest Calculator", "Replay a regular buy, or one lump sum, against bundled daily closes. No live quote."),

  tool("gaming-hardware", "loot-box-calculator", "Loot Box Expected Value", "Expected value per pull, and the chance of a rarity within N pulls."),
  tool("gaming-hardware", "pc-build-cost-estimator", "Gaming PC Build Cost Estimator", "Add the prices you enter for each part of a PC. There is no live price list."),
  tool("gaming-hardware", "library-value-calculator", "Steam Library Value Calculator", "Add what you paid for each game. No Steam account, no import."),
  tool("gaming-hardware", "bracket-generator", "Esports Bracket Generator", "A single-elimination bracket you fill in and click through."),

  tool("creator", "rate-card-calculator", "Creator Rate Card Calculator", "A starting rate range from followers, engagement, and content type — not what a brand will pay."),
  tool("creator", "engagement-rate-calculator", "Engagement Rate Calculator", "Engagement from followers, likes, and comments you type."),
  tool("creator", "best-time-to-post", "Best Time to Post", "A general posting window for a platform and an audience region — not your analytics."),
  tool("creator", "thread-formatter", "Thread Formatter", "Split a long note into numbered posts you can copy."),
  tool("creator", "thumbnail-preview", "Thumbnail A/B Preview", "Compare two thumbnails in a simple video-feed mock."),
  tool("creator", "username-checker", "Username Availability Checker", "Ask Instagram, TikTok, and X whether a username looks taken."),
  tool("creator", "bio-link-builder", "Bio-Link Page Builder", "Stack a few links, preview the page, and download the HTML."),

  tool("ai-tools", "api-cost-calculator", "AI API Cost Calculator", "Estimate a token bill from published per-token prices. Prices can lag."),
  tool("ai-tools", "token-counter", "Prompt Token Counter", "Count tokens in pasted text with a real tokenizer."),
  tool("ai-tools", "coding-tool-cost-calculator", "AI Coding Tool Cost Calculator", "A rough monthly comparison of Cursor, Claude Code, and Copilot from published list prices."),
  tool("ai-tools", "prompt-library", "Prompt Library", "Keep prompts in this browser. They are not synced."),

  tool("calculators", "subscription-audit-calculator", "Subscription Audit", "Add monthly subscriptions and see the annual total — the number people under-count.", "live", { cluster: "household", tags: ["subscriptions", "budget"] }),
  tool("calculators", "expense-splitter", "Expense Splitter", "See who owes whom after a shared spend.", "live", { cluster: "household", tags: ["split", "bill"] }),
  tool("calculators", "side-hustle-tracker", "Side Hustle Tracker", "Log income and expenses and watch the profit. It stays on this page.", "live", { cluster: "household", tags: ["income", "profit"] }),
  tool("calculators", "bnpl-cost-calculator", "BNPL True-Cost Calculator", "What fees add to a plan that is advertised as interest-free.", "live", { cluster: "debt", tags: ["bnpl", "fees"] }),
  tool("calculators", "fire-calculator", "FIRE Calculator", "Years to financial independence on the 4% rule, from the numbers you type.", "live", { cluster: "growth", tags: ["fire", "independence"] }),
  tool("calculators", "gig-tax-estimator", "Gig Economy Tax Estimator", "A rough Australian tax estimate on freelance income beside a wage. Not a lodgement.", "live", { cluster: "pay", tags: ["tax", "freelance"] }),
  tool("calculators", "round-up-investing-estimator", "Round-up Investing Estimator", "How spare change from round-ups adds up over a year.", "live", { cluster: "growth", tags: ["round-up", "investing"] }),
  tool("calculators", "net-worth-calculator", "Net Worth Calculator", "Add assets and liabilities and see the net figure, with a simple breakdown.", "live", { cluster: "household", tags: ["net worth", "assets"] }),
  tool("calculators", "debt-payoff-calculator", "Debt Payoff Calculator", "Estimate when a debt is paid off, and how extra payments change the interest.", "live", { cluster: "debt", tags: ["debt", "payoff"] }),

  tool("business", "resale-profit-calculator", "Resale Profit Calculator", "Net profit after a marketplace fee, shipping, and what the item cost."),

  tool("everyday-fun", "social-battery-checkin", "Social Battery Check-in", "A few short questions and a light read on whether you need downtime."),
  tool("everyday-fun", "screen-time-audit", "Screen Time Audit", "Hours a day by category, then the week and the year. You type the hours."),
  tool("everyday-fun", "carbon-footprint-estimator", "Carbon Footprint Estimator", "A rough streaming and AI estimate from published factors — illustrative, not a meter."),

  tool("developer", "commit-message-generator", "Git Commit Message Generator", "Turn a short description into a conventional commit.", "live", { cluster: "ops", tags: ["git", "commit"] }),
  tool("developer", "rate-limit-calculator", "API Rate-Limit Calculator", "Whether a request limit covers the users you expect.", "live", { cluster: "network", tags: ["rate limit", "api"] }),
  tool("developer", "ai-tool-fit-quiz", "Which AI Coding Tool Fits You", "A short quiz with Cursor, Claude Code, or Copilot as the read.", "live", { cluster: "ai-dev", tags: ["ai", "quiz"] }),
]
